---
title: AlternativeAndSupplementalServices
config:
  layout: elk
---
erDiagram
    Program {
        reference EducationOrganization "I"
        string ProgramId "O"
        string ProgramName "I"
        descriptor ProgramType "I"
        descriptor ProgramCharacteristic "OC"
        descriptor ProgramSponsor "OC"
        reference LearningStandard "OC"
    }
    Staff {
        string StaffUniqueId "I"
        common Name "R"
        common OtherName "OC"
        date BirthDate "O"
        descriptor HighestCompletedLevelOfEducation "O"
        decimal YearsOfPriorProfessionalExperience "O"
        decimal YearsOfPriorTeachingExperience "O"
        string LoginId "O"
        bool HighlyQualifiedTeacher "O"
        common Recognition "OC"
        reference Credential "OC"
        reference Person "O"
        descriptor HighlyQualifiedAcademicSubject "OC"
        common EducatorResearch "O"
        reference EducatorPreparationProgram "OC"
        reference OpenStaffPosition "O"
    }
    GeneralStudentProgramAssociation {
        reference Student "I"
        reference Program "I"
        date BeginDate "I"
        date EndDate "O"
        descriptor ReasonExited "O"
        reference EducationOrganization "I"
        bool ServedOutsideOfRegularSession "O"
        common ProgramParticipationStatus "OC"
    }
    StaffProgramAssociation {
        reference Staff "I"
        reference Program "I"
        date BeginDate "I"
        date EndDate "O"
        bool StudentRecordAccess "O"
    }
    Section {
        string SectionIdentifier "I"
        descriptor SectionType "O"
        integer SequenceOfCourse "O"
        descriptor EducationalEnvironment "O"
        descriptor MediumOfInstruction "O"
        descriptor PopulationServed "O"
        common AvailableCredits "O"
        descriptor SectionCharacteristic "OC"
        descriptor InstructionLanguage "O"
        reference CourseOffering "I"
        reference LocationSchool "O"
        reference Location "O"
        reference ClassPeriod "OC"
        reference Program "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor OfferedGradeLevel "OC"
        bool OfficialAttendancePeriod "O"
        string SectionName "O"
    }
    StudentSectionAssociation {
        reference Student "I"
        reference Section "I"
        date BeginDate "I"
        date EndDate "O"
        bool HomeroomIndicator "O"
        descriptor RepeatIdentifier "O"
        bool TeacherStudentDataLinkExclusion "O"
        descriptor AttemptStatus "O"
        reference Program "OC"
        common DualCredit "O"
    }
    Student {
        string StudentUniqueId "I"
        common Name "R"
        common OtherName "OC"
        common BirthData "R"
        reference Person "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        string NameOfInstitution "R"
        string ShortNameOfInstitution "O"
        descriptor EducationOrganizationCategory "RC"
        common Address "OC"
        common InternationalAddress "OC"
        common InstitutionTelephone "OC"
        string WebSite "O"
        descriptor OperationalStatus "O"
        common EducationOrganizationIndicator "OC"
    }
    StudentSectionAttendanceEvent {
        common AttendanceEvent "R"
        reference Student "I"
        reference Section "I"
        integer SectionAttendanceDuration "O"
        time ArrivalTime "O"
        time DepartureTime "O"
        reference ClassPeriod "OC"
    }
    StudentSchoolAttendanceEvent {
        common AttendanceEvent "R"
        reference Student "I"
        reference School "I"
        reference Session "I"
        integer SchoolAttendanceDuration "O"
        time ArrivalTime "O"
        time DepartureTime "O"
    }
    StudentProgramAttendanceEvent {
        common AttendanceEvent "R"
        reference Student "I"
        reference EducationOrganization "I"
        reference Program "I"
        integer ProgramAttendanceDuration "O"
    }
    StudentSpecialEducationProgramEligibilityAssociation {
        reference EducationOrganization "I"
        reference Student "I"
        reference Program "I"
        date ConsentToEvaluationReceivedDate "I"
        date OriginalECIServicesDate "O"
        descriptor IDEAPart "R"
        date ConsentToEvaluationDate "O"
        bool EvaluationCompleteIndicator "O"
        date EligibilityEvaluationDate "O"
        descriptor EligibilityEvaluationType "O"
        descriptor EvaluationDelayReason "O"
        string EvaluationLateReason "O"
        integer EvaluationDelayDays "O"
        date EligibilityDeterminationDate "O"
        bool IDEAIndicator "O"
        descriptor EligibilityDelayReason "O"
        date TransitionNotificationDate "O"
        date TransitionConferenceDate "O"
        date EligibilityConferenceDate "O"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor CharterStatus "O"
        descriptor TitleIPartASchoolDesignation "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        descriptor AdministrativeFundingControl "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor FederalLocaleCode "O"
        reference PostSecondaryInstitution "O"
        bool ImprovingSchool "O"
        descriptor AccreditationStatus "O"
    }
    EducationOrganization ||--o{ Program : "has associated"
    Student ||--o{ Program : "has associated"
    Program ||--o{ Staff : "has associated"
    Section ||--o{ Program : "has associated"
    Student ||--o{ School : "has associated"
    Student ||--o{ GeneralStudentProgramAssociation : "has associated"
    Student ||--o{ StaffProgramAssociation : "has associated"
    Staff ||--o{ StaffProgramAssociation : "has associated"
    Student ||--o{ StudentSectionAssociation : "has associated"
    Section ||--o{ StudentSectionAssociation : "has associated"
    Student ||--o{ StudentSpecialEducationProgramEligibilityAssociation : "has associated"
    StudentSectionAttendanceEvent ||--o{ Student : "has associated"
    StudentSectionAttendanceEvent ||--o{ Section : "has associated"
    StudentSchoolAttendanceEvent ||--o{ School : "has associated"
    StudentSchoolAttendanceEvent ||--o{ Student : "has associated"
    StudentProgramAttendanceEvent ||--o{ EducationOrganization : "has associated"
    StudentProgramAttendanceEvent ||--o{ Program : "has associated"
