---
title: Assessment
config:
  layout: elk
---
erDiagram
    Assessment {
        string AssessmentIdentifier "I"
        string AssessmentTitle "R"
        common AssessmentIdentificationCode "OC"
        descriptor AssessmentCategory "O"
        descriptor AcademicSubject "R"
        descriptor AssessedGradeLevel "OC"
        common AssessmentScore "OC"
        common AssessmentPerformanceLevel "OC"
        common ContentStandard "O"
        string AssessmentForm "O"
        descriptor Language "OC"
        integer AssessmentVersion "O"
        date RevisionDate "O"
        decimal MaxRawScore "O"
        string Nomenclature "O"
        common AssessmentPeriod "OC"
        string AssessmentFamily "O"
        choice SectionOrProgramChoice "O"
        string Namespace "I"
        reference EducationOrganization "O"
        bool AdaptiveAssessment "O"
        descriptor PlatformType "OC"
    }
    StudentAssessment {
        string StudentAssessmentIdentifier "I"
        datetime AdministrationDate "O"
        datetime AdministrationEndDate "O"
        string SerialNumber "O"
        descriptor AdministrationLanguage "O"
        descriptor AdministrationEnvironment "O"
        descriptor Accommodation "OC"
        descriptor RetestIndicator "O"
        descriptor ReasonNotTested "O"
        common ScoreResult "OC"
        descriptor AssessedGradeLevel "O"
        descriptor WhenAssessedGradeLevel "O"
        common PerformanceLevel "OC"
        descriptor EventCircumstance "O"
        string EventDescription "O"
        reference Student "I"
        reference Assessment "I"
        common StudentAssessmentItem "OC"
        common StudentObjectiveAssessment "OC"
        enumeration SchoolYear "R"
        descriptor PlatformType "O"
        common AssessmentPeriod "O"
        integer AssessedMinutes "O"
        reference ReportedSchool "O"
        string ReportedSchoolIdentifier "O"
        common StudentAssessmentIndicator "OC"
    }
    ObjectiveAssessment {
        string IdentificationCode "I"
        decimal MaxRawScore "O"
        common AssessmentPerformanceLevel "OC"
        percent PercentOfAssessment "O"
        string Nomenclature "O"
        string Description "O"
        reference AssessmentItem "OC"
        reference LearningStandard "OC"
        reference ParentObjectiveAssessment "OC"
        reference Assessment "I"
        common AssessmentScore "OC"
        descriptor AcademicSubject "O"
    }
    AssessmentItem {
        string IdentificationCode "I"
        descriptor AssessmentItemCategory "O"
        decimal MaxRawScore "O"
        string ItemText "O"
        common PossibleResponse "OC"
        duration ExpectedTimeAssessed "O"
        string Nomenclature "O"
        reference LearningStandard "OC"
        reference Assessment "I"
        string AssessmentItemURI "O"
    }
    LearningStandard {
        string LearningStandardId "I"
        common LearningStandardIdentificationCode "OC"
        string Description "R"
        string LearningStandardItemCode "O"
        common ContentStandard "R"
        string URI "O"
        descriptor GradeLevel "RC"
        descriptor AcademicSubject "RC"
        string CourseTitle "O"
        string SuccessCriteria "O"
        reference ParentLearningStandard "O"
        string Namespace "R"
        descriptor LearningStandardCategory "O"
        descriptor LearningStandardScope "O"
    }
    LearningStandardEquivalenceAssociation {
        reference SourceLearningStandard "I"
        reference TargetLearningStandard "I"
        string Namespace "I"
        date EffectiveDate "O"
        descriptor LearningStandardEquivalenceStrength "O"
        string LearningStandardEquivalenceStrengthDescription "O"
    }
    AssessmentScoreRangeLearningStandard {
        reference Assessment "I"
        reference LearningStandard "RC"
        string ScoreRangeId "I"
        descriptor AssessmentReportingMethod "O"
        string MinimumScore "R"
        string MaximumScore "R"
        reference ObjectiveAssessment "O"
    }
    StudentAssessmentEducationOrganizationAssociation {
        reference StudentAssessment "I"
        reference EducationOrganization "I"
        descriptor EducationOrganizationAssociationType "I"
        enumeration SchoolYear "O"
    }
    Student {
        string StudentUniqueId "I"
        common Name "R"
        common OtherName "OC"
        common BirthData "R"
        reference Person "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        string NameOfInstitution "R"
        string ShortNameOfInstitution "O"
        descriptor EducationOrganizationCategory "RC"
        common Address "OC"
        common InternationalAddress "OC"
        common InstitutionTelephone "OC"
        string WebSite "O"
        descriptor OperationalStatus "O"
        common EducationOrganizationIndicator "OC"
    }
    Section {
        string SectionIdentifier "I"
        descriptor SectionType "O"
        integer SequenceOfCourse "O"
        descriptor EducationalEnvironment "O"
        descriptor MediumOfInstruction "O"
        descriptor PopulationServed "O"
        common AvailableCredits "O"
        descriptor SectionCharacteristic "OC"
        descriptor InstructionLanguage "O"
        reference CourseOffering "I"
        reference LocationSchool "O"
        reference Location "O"
        reference ClassPeriod "OC"
        reference Program "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor OfferedGradeLevel "OC"
        bool OfficialAttendancePeriod "O"
        string SectionName "O"
    }
    Program {
        reference EducationOrganization "I"
        string ProgramId "O"
        string ProgramName "I"
        descriptor ProgramType "I"
        descriptor ProgramCharacteristic "OC"
        descriptor ProgramSponsor "OC"
        reference LearningStandard "OC"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor CharterStatus "O"
        descriptor TitleIPartASchoolDesignation "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        descriptor AdministrativeFundingControl "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor FederalLocaleCode "O"
        reference PostSecondaryInstitution "O"
        bool ImprovingSchool "O"
        descriptor AccreditationStatus "O"
    }
    StudentAssessment ||--o{ Student : "has associated"
    StudentAssessment ||--o{ Assessment : "has associated"
    StudentAssessment ||--o{ EducationOrganization : "has associated"
    StudentAssessmentEducationOrganizationAssociation ||--o{ StudentAssessment : "has associated"
    StudentAssessmentEducationOrganizationAssociation ||--o{ EducationOrganization : "has associated"
    Assessment ||--o{ EducationOrganization : "has associated"
    Assessment ||--o{ Section : "has associated"
    Assessment ||--o{ Program : "has associated"
    ObjectiveAssessment ||--o{ Assessment : "has associated"
    ObjectiveAssessment ||--o{ ObjectiveAssessment : "has associated"
    ObjectiveAssessment ||--o{ AssessmentItem : "has associated"
    ObjectiveAssessment ||--o{ LearningStandard : "has associated"
    AssessmentItem ||--o{ LearningStandard : "has associated"
    AssessmentScoreRangeLearningStandard ||--o{ LearningStandard : "has associated"
    LearningStandardEquivalenceAssociation ||--o{ LearningStandard : "has associated"
    LearningStandard ||--o{ LearningStandard : "has associated"
    Program ||--o{ LearningStandard : "has associated"
    Section ||--o{ Program : "has associated"
    Student ||--o{ Section : "has associated"
    Student ||--o{ Program : "has associated"
