---
title: Assessment-AssessmentMetaData
config:
  layout: elk
---
erDiagram
    Assessment {
        string AssessmentIdentifier "I"
        string AssessmentTitle "R"
        common AssessmentIdentificationCode "OC"
        descriptor AssessmentCategory "O"
        descriptor AcademicSubject "R"
        descriptor AssessedGradeLevel "OC"
        common AssessmentScore "OC"
        common AssessmentPerformanceLevel "OC"
        common ContentStandard "O"
        string AssessmentForm "O"
        descriptor Language "OC"
        integer AssessmentVersion "O"
        date RevisionDate "O"
        decimal MaxRawScore "O"
        string Nomenclature "O"
        common AssessmentPeriod "OC"
        string AssessmentFamily "O"
        choice SectionOrProgramChoice "O"
        string Namespace "I"
        reference EducationOrganization "O"
        bool AdaptiveAssessment "O"
        descriptor PlatformType "OC"
    }
    ObjectiveAssessment {
        string IdentificationCode "I"
        decimal MaxRawScore "O"
        common AssessmentPerformanceLevel "OC"
        percent PercentOfAssessment "O"
        string Nomenclature "O"
        string Description "O"
        reference AssessmentItem "OC"
        reference LearningStandard "OC"
        reference ParentObjectiveAssessment "OC"
        reference Assessment "I"
        common AssessmentScore "OC"
        descriptor AcademicSubject "O"
    }
    AssessmentItem {
        string IdentificationCode "I"
        descriptor AssessmentItemCategory "O"
        decimal MaxRawScore "O"
        string ItemText "O"
        common PossibleResponse "OC"
        duration ExpectedTimeAssessed "O"
        string Nomenclature "O"
        reference LearningStandard "OC"
        reference Assessment "I"
        string AssessmentItemURI "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        string NameOfInstitution "R"
        string ShortNameOfInstitution "O"
        descriptor EducationOrganizationCategory "RC"
        common Address "OC"
        common InternationalAddress "OC"
        common InstitutionTelephone "OC"
        string WebSite "O"
        descriptor OperationalStatus "O"
        common EducationOrganizationIndicator "OC"
    }
    Section {
        string SectionIdentifier "I"
        descriptor SectionType "O"
        integer SequenceOfCourse "O"
        descriptor EducationalEnvironment "O"
        descriptor MediumOfInstruction "O"
        descriptor PopulationServed "O"
        common AvailableCredits "O"
        descriptor SectionCharacteristic "OC"
        descriptor InstructionLanguage "O"
        reference CourseOffering "I"
        reference LocationSchool "O"
        reference Location "O"
        reference ClassPeriod "OC"
        reference Program "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor OfferedGradeLevel "OC"
        bool OfficialAttendancePeriod "O"
        string SectionName "O"
    }
    Program {
        reference EducationOrganization "I"
        string ProgramId "O"
        string ProgramName "I"
        descriptor ProgramType "I"
        descriptor ProgramCharacteristic "OC"
        descriptor ProgramSponsor "OC"
        reference LearningStandard "OC"
    }
    ObjectiveAssessment ||--o{ ObjectiveAssessment : "has associated"
    ObjectiveAssessment ||--o{ AssessmentItem : "has associated"
    ObjectiveAssessment ||--o{ Assessment : "has associated"
    AssessmentItem ||--o{ Assessment : "has associated"
    Assessment ||--o{ EducationOrganization : "has associated"
    Assessment ||--o{ Section : "has associated"
    Assessment ||--o{ Program : "has associated"
    Section ||--o{ Program : "has associated"
