---
title: AssessmentRegistration
config:
  layout: elk
---
erDiagram
    Assessment {
        string AssessmentIdentifier "I"
        string AssessmentTitle "R"
        common AssessmentIdentificationCode "OC"
        descriptor AssessmentCategory "O"
        descriptor AcademicSubject "R"
        descriptor AssessedGradeLevel "OC"
        common AssessmentScore "OC"
        common AssessmentPerformanceLevel "OC"
        common ContentStandard "O"
        string AssessmentForm "O"
        descriptor Language "OC"
        integer AssessmentVersion "O"
        date RevisionDate "O"
        decimal MaxRawScore "O"
        string Nomenclature "O"
        common AssessmentPeriod "OC"
        string AssessmentFamily "O"
        choice SectionOrProgramChoice "O"
        string Namespace "I"
        reference EducationOrganization "O"
        bool AdaptiveAssessment "O"
        descriptor PlatformType "OC"
    }
    AssessmentAdministration {
        reference AssigningEducationOrganization "I"
        reference Assessment "I"
        string AdministrationIdentifier "I"
        common AssessmentAdministrationPeriod "OC"
        reference AssessmentBatteryPart "OC"
    }
    AssessmentAdministrationParticipation {
        reference AssessmentAdministration "I"
        reference ParticipatingEducationOrganization "I"
        common AdministrationPointOfContact "OC"
    }
    AssessmentBatteryPart {
        reference Assessment "I"
        string AssessmentBatteryPartName "I"
        reference ObjectiveAssessment "OC"
    }
    ObjectiveAssessment {
        string IdentificationCode "I"
        decimal MaxRawScore "O"
        common AssessmentPerformanceLevel "OC"
        percent PercentOfAssessment "O"
        string Nomenclature "O"
        string Description "O"
        reference AssessmentItem "OC"
        reference LearningStandard "OC"
        reference ParentObjectiveAssessment "OC"
        reference Assessment "I"
        common AssessmentScore "OC"
        descriptor AcademicSubject "O"
    }
    StudentAssessmentRegistration {
        reference AssessmentAdministration "I"
        reference StudentDemographic "I"
        reference StudentSchoolAssociation "R"
        descriptor AssessmentAccommodation "OC"
        common AssessmentCustomization "OC"
        reference ReportingEducationOrganization "O"
        reference TestingEducationOrganization "O"
        descriptor AssessmentGradeLevel "O"
        descriptor PlatformType "O"
        reference ScheduledStudentEducationOrganizationAssessmentAccommodation "O"
    }
    StudentAssessmentRegistrationBatteryPartAssociation {
        reference StudentAssessmentRegistration "I"
        reference AssessmentBatteryPart "I"
        descriptor Accommodation "OC"
    }
    StudentEducationOrganizationAssessmentAccommodation {
        reference EducationOrganization "I"
        reference Student "I"
        descriptor GeneralAccommodation "OC"
    }
    Student {
        string StudentUniqueId "I"
        common Name "R"
        common OtherName "OC"
        common BirthData "R"
        reference Person "O"
    }
    StudentDemographic {
        reference Student "I"
        reference EducationOrganization "I"
        descriptor AncestryEthnicOrigin "OC"
        common Citizenship "O"
        common Disability "OC"
        descriptor EconomicDisadvantage "O"
        string GenderIdentity "O"
        bool HispanicLatinoEthnicity "O"
        common Language "OC"
        descriptor LimitedEnglishProficiency "O"
        descriptor Race "OC"
        descriptor Sex "O"
        common StudentCharacteristic "OC"
        descriptor SupporterMilitaryConnection "O"
        descriptor TribalAffiliation "OC"
    }
    StudentSchoolAssociation {
        reference Student "I"
        reference School "I"
        bool PrimarySchool "O"
        enumeration SchoolYear "O"
        date EntryDate "I"
        descriptor EntryGradeLevel "R"
        descriptor EntryGradeLevelReason "O"
        descriptor EntryType "O"
        bool RepeatGradeIndicator "O"
        enumeration ClassOfSchoolYear "O"
        bool SchoolChoiceTransfer "O"
        date ExitWithdrawDate "O"
        descriptor ExitWithdrawType "O"
        descriptor EducationPlan "OC"
        descriptor ResidencyStatus "O"
        reference GraduationPlan "O"
        reference AlternativeGraduationPlan "OC"
        bool EmployedWhileEnrolled "O"
        reference Calendar "O"
        decimal FullTimeEquivalency "O"
        bool TermCompletionIndicator "O"
        reference NextYearSchool "O"
        descriptor NextYearGradeLevel "O"
        bool SchoolChoice "O"
        descriptor SchoolChoiceBasis "O"
        descriptor EnrollmentType "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        string NameOfInstitution "R"
        string ShortNameOfInstitution "O"
        descriptor EducationOrganizationCategory "RC"
        common Address "OC"
        common InternationalAddress "OC"
        common InstitutionTelephone "OC"
        string WebSite "O"
        descriptor OperationalStatus "O"
        common EducationOrganizationIndicator "OC"
    }
    LocalEducationAgency {
        integer LocalEducationAgencyId "I"
        descriptor LocalEducationAgencyCategory "R"
        descriptor CharterStatus "O"
        common LocalEducationAgencyAccountability "OC"
        common LocalEducationAgencyFederalFunds "OC"
        reference ParentLocalEducationAgency "O"
        reference EducationServiceCenter "O"
        reference StateEducationAgency "O"
        descriptor FederalLocaleCode "O"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor CharterStatus "O"
        descriptor TitleIPartASchoolDesignation "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        descriptor AdministrativeFundingControl "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor FederalLocaleCode "O"
        reference PostSecondaryInstitution "O"
        bool ImprovingSchool "O"
        descriptor AccreditationStatus "O"
    }
    School ||--o{ EducationOrganization : "has associated"
    School ||--o{ LocalEducationAgency : "has associated"
    LocalEducationAgency ||--o{ EducationOrganization : "has associated"
    AssessmentBatteryPart ||--o{ Assessment : "has associated"
    AssessmentBatteryPart ||--o{ ObjectiveAssessment : "has associated"
    ObjectiveAssessment ||--o{ Assessment : "has associated"
    AssessmentAdministration ||--o{ AssessmentBatteryPart : "has associated"
    AssessmentAdministration ||--o{ EducationOrganization : "has associated"
    AssessmentAdministrationParticipation ||--o{ AssessmentAdministration : "has associated"
    AssessmentAdministrationParticipation ||--o{ EducationOrganization : "has associated"
    StudentAssessmentRegistration ||--o{ AssessmentAdministration : "has associated"
    StudentAssessmentRegistration ||--o{ StudentSchoolAssociation : "has associated"
    StudentAssessmentRegistration ||--o{ EducationOrganization : "has associated"
    StudentAssessmentRegistration ||--o{ StudentEducationOrganizationAssessmentAccommodation : "has associated"
    StudentAssessmentRegistrationBatteryPartAssociation ||--o{ StudentAssessmentRegistration : "has associated"
    StudentAssessmentRegistrationBatteryPartAssociation ||--o{ AssessmentBatteryPart : "has associated"
    StudentEducationOrganizationAssessmentAccommodation ||--o{ Student : "has associated"
    StudentEducationOrganizationAssessmentAccommodation ||--o{ EducationOrganization : "has associated"
    StudentSchoolAssociation ||--o{ Student : "has associated"
    StudentSchoolAssociation ||--o{ EducationOrganization : "has associated"
    StudentDemographic ||--o{ Student : "has associated"
