---
title: Credential
config:
  layout: elk
---
erDiagram
    Credential {
        string CredentialIdentifier "I"
        descriptor StateOfIssueStateAbbreviation "I"
        string Namespace "R"
        descriptor CredentialType "R"
        date IssuanceDate "R"
        descriptor CredentialField "O"
        date EffectiveDate "O"
        date ExpirationDate "O"
        descriptor TeachingCredential "O"
        descriptor TeachingCredentialBasis "O"
        descriptor GradeLevel "OC"
        descriptor AcademicSubject "OC"
        string CredentialEndorsement "OC"
        string CertificationTitle "O"
        reference Certification "O"
        descriptor CertificationRoute "O"
        bool BoardCertificationIndicator "O"
        descriptor CredentialStatus "O"
        date CredentialStatusDate "O"
        reference Person "O"
        reference StudentAcademicRecord "OC"
        descriptor EducatorRole "O"
    }
    CredentialEvent {
        descriptor CredentialEventType "I"
        date CredentialEventDate "I"
        reference Credential "I"
        string CredentialEventReason "O"
    }
    Certification {
        string CertificationIdentifier "I"
        string Namespace "I"
        string CertificationTitle "R"
        reference EducationOrganization "O"
        descriptor CertificationLevel "O"
        descriptor CertificationField "O"
        descriptor GradeLevel "OC"
        descriptor CertificationRoute "OC"
        descriptor CertificationStandard "O"
        descriptor MinimumDegree "O"
        descriptor EducatorRole "O"
        descriptor PopulationServed "O"
        descriptor InstructionalSetting "O"
        reference CertificationExam "OC"
        date EffectiveDate "O"
        date EndDate "O"
    }
    CertificationExam {
        string CertificationExamIdentifier "I"
        string Namespace "I"
        string CertificationExamTitle "R"
        reference EducationOrganization "O"
        descriptor CertificationExamType "O"
        date EffectiveDate "O"
        date EndDate "O"
    }
    CertificationExamResult {
        reference CertificationExam "I"
        reference Person "I"
        date CertificationExamDate "I"
        integer AttemptNumber "O"
        decimal CertificationExamScore "O"
        bool CertificationExamPassIndicator "O"
        descriptor CertificationExamStatus "O"
        reference CertificationExamStudentAssessment "O"
    }
    Person {
        string PersonId "I"
        descriptor SourceSystem "I"
    }
    Staff {
        string StaffUniqueId "I"
        common Name "R"
        common OtherName "OC"
        date BirthDate "O"
        descriptor HighestCompletedLevelOfEducation "O"
        decimal YearsOfPriorProfessionalExperience "O"
        decimal YearsOfPriorTeachingExperience "O"
        string LoginId "O"
        bool HighlyQualifiedTeacher "O"
        common Recognition "OC"
        reference Credential "OC"
        reference Person "O"
        descriptor HighlyQualifiedAcademicSubject "OC"
        common EducatorResearch "O"
        reference EducatorPreparationProgram "OC"
        reference OpenStaffPosition "O"
    }
    StudentAcademicRecord {
        reference Student "I"
        reference EducationOrganization "I"
        enumeration SchoolYear "I"
        descriptor Term "I"
        common AcademicHonor "OC"
        common ClassRanking "O"
        common CumulativeAttemptedCredits "O"
        common CumulativeEarnedCredits "O"
        common SessionAttemptedCredits "O"
        common SessionEarnedCredits "O"
        common Diploma "OC"
        common GradePointAverage "OC"
        date ProjectedGraduationDate "O"
        common Recognition "OC"
        reference ReportCard "OC"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        string NameOfInstitution "R"
        string ShortNameOfInstitution "O"
        descriptor EducationOrganizationCategory "RC"
        common Address "OC"
        common InternationalAddress "OC"
        common InstitutionTelephone "OC"
        string WebSite "O"
        descriptor OperationalStatus "O"
        common EducationOrganizationIndicator "OC"
    }
    StudentAssessment {
        string StudentAssessmentIdentifier "I"
        datetime AdministrationDate "O"
        datetime AdministrationEndDate "O"
        string SerialNumber "O"
        descriptor AdministrationLanguage "O"
        descriptor AdministrationEnvironment "O"
        descriptor Accommodation "OC"
        descriptor RetestIndicator "O"
        descriptor ReasonNotTested "O"
        common ScoreResult "OC"
        descriptor AssessedGradeLevel "O"
        descriptor WhenAssessedGradeLevel "O"
        common PerformanceLevel "OC"
        descriptor EventCircumstance "O"
        string EventDescription "O"
        reference Student "I"
        reference Assessment "I"
        common StudentAssessmentItem "OC"
        common StudentObjectiveAssessment "OC"
        enumeration SchoolYear "R"
        descriptor PlatformType "O"
        common AssessmentPeriod "O"
        integer AssessedMinutes "O"
        reference ReportedSchool "O"
        string ReportedSchoolIdentifier "O"
        common StudentAssessmentIndicator "OC"
    }
    Staff ||--o{ Person : "has associated"
    Staff ||--o{ EducationOrganization : "has associated"
    Credential ||--o{ Staff : "has associated"
    Credential ||--o{ Person : "has associated"
    Credential ||--o{ Certification : "has associated"
    Credential ||--o{ StudentAcademicRecord : "has associated"
    CredentialEvent ||--o{ Credential : "has associated"
    Certification ||--o{ CertificationExam : "has associated"
    Certification ||--o{ EducationOrganization : "has associated"
    CertificationExam ||--o{ EducationOrganization : "has associated"
    CertificationExamResult ||--o{ CertificationExam : "has associated"
    CertificationExamResult ||--o{ Person : "has associated"
    CertificationExamResult ||--o{ StudentAssessment : "has associated"
