---
title: EducatorPreparationProgram
config:
  layout: elk
---
erDiagram
    Candidate {
        string CandidateIdentifier "I"
        common Name "R"
        common OtherName "OC"
        descriptor Sex "R"
        string GenderIdentity "O"
        common BirthData "R"
        common Address "OC"
        common InternationalAddress "OC"
        common Telephone "OC"
        common ElectronicMail "OC"
        string ProfileThumbnail "O"
        bool HispanicLatinoEthnicity "O"
        descriptor Race "OC"
        common Citizenship "O"
        descriptor EconomicDisadvantage "O"
        common CandidateCharacteristic "OC"
        descriptor LimitedEnglishProficiency "O"
        common Language "OC"
        common Disability "OC"
        string DisplacementStatus "O"
        common CandidateIndicator "OC"
        string LoginId "O"
        decimal TuitionCost "O"
        common BackgroundCheck "O"
        descriptor EnglishLanguageExam "O"
        descriptor PreviousCareer "O"
        bool FirstGenerationStudent "O"
        common EPPProgramDegree "OC"
        reference Person "O"
    }
    CandidateIdentificationCode {
        reference Candidate "I"
        descriptor CandidateIdentificationSystem "I"
        reference EducationOrganization "I"
        string IdentificationCode "R"
        string AssigningOrganizationIdentificationCode "O"
    }
    EducatorPreparationProgram {
        reference EducationOrganization "I"
        string ProgramId "O"
        string ProgramName "I"
        descriptor ProgramType "I"
        descriptor GradeLevel "OC"
        descriptor AccreditationStatus "O"
    }
    FieldworkExperience {
        string FieldworkIdentifier "I"
        reference Student "I"
        reference School "O"
        reference EducatorPreparationProgram "O"
        descriptor FieldworkType "R"
        decimal HoursCompleted "O"
        date BeginDate "I"
        date EndDate "O"
        common Coteaching "O"
    }
    CandidateEducatorPreparationProgramAssociation {
        reference Candidate "I"
        reference EducatorPreparationProgram "I"
        date BeginDate "I"
        date EndDate "O"
        descriptor ReasonExited "O"
        common CandidateIndicator "OC"
        descriptor EPPProgramPathway "O"
        common DegreeSpecialization "OC"
        common CohortYear "OC"
        reference Application "O"
    }
    CandidateRelationshipToStaffAssociation {
        reference Candidate "I"
        reference Staff "I"
        descriptor StaffToCandidateRelationship "O"
        date BeginDate "R"
        date EndDate "O"
    }
    StaffEducatorPreparationProgramAssociation {
        reference Staff "I"
        reference EducatorPreparationProgram "I"
        date BeginDate "R"
        date EndDate "O"
        bool Completer "O"
    }
    Person {
        string PersonId "I"
        descriptor SourceSystem "I"
    }
    Staff {
        string StaffUniqueId "I"
        common Name "R"
        common OtherName "OC"
        date BirthDate "O"
        descriptor HighestCompletedLevelOfEducation "O"
        decimal YearsOfPriorProfessionalExperience "O"
        decimal YearsOfPriorTeachingExperience "O"
        string LoginId "O"
        bool HighlyQualifiedTeacher "O"
        common Recognition "OC"
        reference Credential "OC"
        reference Person "O"
        descriptor HighlyQualifiedAcademicSubject "OC"
        common EducatorResearch "O"
        reference EducatorPreparationProgram "OC"
        reference OpenStaffPosition "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        string NameOfInstitution "R"
        string ShortNameOfInstitution "O"
        descriptor EducationOrganizationCategory "RC"
        common Address "OC"
        common InternationalAddress "OC"
        common InstitutionTelephone "OC"
        string WebSite "O"
        descriptor OperationalStatus "O"
        common EducationOrganizationIndicator "OC"
    }
    Section {
        string SectionIdentifier "I"
        descriptor SectionType "O"
        integer SequenceOfCourse "O"
        descriptor EducationalEnvironment "O"
        descriptor MediumOfInstruction "O"
        descriptor PopulationServed "O"
        common AvailableCredits "O"
        descriptor SectionCharacteristic "OC"
        descriptor InstructionLanguage "O"
        reference CourseOffering "I"
        reference LocationSchool "O"
        reference Location "O"
        reference ClassPeriod "OC"
        reference Program "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor OfferedGradeLevel "OC"
        bool OfficialAttendancePeriod "O"
        string SectionName "O"
    }
    Candidate ||--o{ Person : "has associated"
    Staff ||--o{ Person : "has associated"
    Candidate ||--o{ EducatorPreparationProgram : "has associated"
    CandidateEducatorPreparationProgramAssociation ||--o{ Candidate : "has associated"
    CandidateEducatorPreparationProgramAssociation ||--o{ EducatorPreparationProgram : "has associated"
    Staff ||--o{ Candidate : "has associated"
    CandidateRelationshipToStaffAssociation ||--o{ Candidate : "has associated"
    CandidateRelationshipToStaffAssociation ||--o{ Staff : "has associated"
    StaffEducatorPreparationProgramAssociation ||--o{ Staff : "has associated"
    StaffEducatorPreparationProgramAssociation ||--o{ EducatorPreparationProgram : "has associated"
    EducationOrganization ||--o{ EducatorPreparationProgram : "has associated"
    Staff ||--o{ EducationOrganization : "has associated"
    FieldworkExperience ||--o{ EducatorPreparationProgram : "has associated"
    FieldworkExperience ||--o{ Section : "has associated"
    CandidateIdentificationCode ||--o{ Candidate : "has associated"
    CandidateIdentificationCode ||--o{ EducationOrganization : "has associated"
    EducationOrganization ||--o{ EducationOrganization : "has associated"
