---
title: Enrollment
config:
  layout: elk
---
erDiagram
    Student {
        string StudentUniqueId "I"
        common Name "R"
        common OtherName "OC"
        common BirthData "R"
        reference Person "O"
    }
    StudentDirectory {
        reference Student "I"
        reference EducationOrganization "I"
        common Address "OC"
        common ElectronicMail "OC"
        common InternationalAddress "OC"
        common Telephone "OC"
    }
    StudentDemographic {
        reference Student "I"
        reference EducationOrganization "I"
        descriptor AncestryEthnicOrigin "OC"
        common Citizenship "O"
        common Disability "OC"
        descriptor EconomicDisadvantage "O"
        string GenderIdentity "O"
        bool HispanicLatinoEthnicity "O"
        common Language "OC"
        descriptor LimitedEnglishProficiency "O"
        descriptor Race "OC"
        descriptor Sex "O"
        common StudentCharacteristic "OC"
        descriptor SupporterMilitaryConnection "O"
        descriptor TribalAffiliation "OC"
    }
    StudentIdentificationCode {
        reference Student "I"
        descriptor StudentIdentificationSystem "I"
        reference EducationOrganization "I"
        string IdentificationCode "R"
        string AssigningOrganizationIdentificationCode "O"
    }
    StudentSchoolAssociation {
        reference Student "I"
        reference School "I"
        bool PrimarySchool "O"
        enumeration SchoolYear "O"
        date EntryDate "I"
        descriptor EntryGradeLevel "R"
        descriptor EntryGradeLevelReason "O"
        descriptor EntryType "O"
        bool RepeatGradeIndicator "O"
        enumeration ClassOfSchoolYear "O"
        bool SchoolChoiceTransfer "O"
        date ExitWithdrawDate "O"
        descriptor ExitWithdrawType "O"
        descriptor EducationPlan "OC"
        descriptor ResidencyStatus "O"
        reference GraduationPlan "O"
        reference AlternativeGraduationPlan "OC"
        bool EmployedWhileEnrolled "O"
        reference Calendar "O"
        decimal FullTimeEquivalency "O"
        bool TermCompletionIndicator "O"
        reference NextYearSchool "O"
        descriptor NextYearGradeLevel "O"
        bool SchoolChoice "O"
        descriptor SchoolChoiceBasis "O"
        descriptor EnrollmentType "O"
    }
    StudentEducationOrganizationAssociation {
        reference Student "I"
        reference EducationOrganization "I"
        string ProfileThumbnail "O"
        common CohortYear "OC"
        common StudentIndicator "OC"
        string LoginId "O"
        descriptor PrimaryLearningDeviceAwayFromSchool "O"
        descriptor PrimaryLearningDeviceAccess "O"
        descriptor PrimaryLearningDeviceProvider "O"
        bool InternetAccessInResidence "O"
        descriptor BarrierToInternetAccessInResidence "O"
        descriptor InternetAccessTypeInResidence "O"
        descriptor InternetPerformanceInResidence "O"
        common DisplacedStudent "OC"
    }
    StudentEducationOrganizationResponsibilityAssociation {
        reference Student "I"
        reference EducationOrganization "I"
        descriptor Responsibility "I"
        date BeginDate "I"
        date EndDate "O"
        reference ResponsibleEducationOrganization "O"
    }
    GraduationPlan {
        descriptor GraduationPlanType "I"
        bool IndividualPlan "O"
        common TotalRequiredCredits "R"
        common CreditsBySubject "OC"
        common CreditsByCourse "OC"
        common CreditsByCreditCategory "OC"
        reference EducationOrganization "I"
        enumeration GraduationSchoolYear "I"
        common RequiredAssessment "OC"
        common RequiredCertification "OC"
    }
    CrisisEvent {
    }
    StudentTransportation {
        reference Student "I"
        reference TransportationEducationOrganization "I"
        descriptor TransportationPublicExpenseEligibilityType "O"
        descriptor TransportationType "O"
        string SpecialAccommodationRequirements "O"
        common StudentBusDetails "O"
    }
    AccountabilityRating {
        reference EducationOrganization "I"
        string RatingTitle "I"
        string Rating "R"
        date RatingDate "O"
        enumeration SchoolYear "I"
        string RatingOrganization "O"
        string RatingProgram "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        string NameOfInstitution "R"
        string ShortNameOfInstitution "O"
        descriptor EducationOrganizationCategory "RC"
        common Address "OC"
        common InternationalAddress "OC"
        common InstitutionTelephone "OC"
        string WebSite "O"
        descriptor OperationalStatus "O"
        common EducationOrganizationIndicator "OC"
    }
    LocalEducationAgency {
        integer LocalEducationAgencyId "I"
        descriptor LocalEducationAgencyCategory "R"
        descriptor CharterStatus "O"
        common LocalEducationAgencyAccountability "OC"
        common LocalEducationAgencyFederalFunds "OC"
        reference ParentLocalEducationAgency "O"
        reference EducationServiceCenter "O"
        reference StateEducationAgency "O"
        descriptor FederalLocaleCode "O"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor CharterStatus "O"
        descriptor TitleIPartASchoolDesignation "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        descriptor AdministrativeFundingControl "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor FederalLocaleCode "O"
        reference PostSecondaryInstitution "O"
        bool ImprovingSchool "O"
        descriptor AccreditationStatus "O"
    }
    StudentDirectory ||--o{ Student : "has associated"
    StudentDirectory ||--o{ EducationOrganization : "has associated"
    StudentDemographic ||--o{ Student : "has associated"
    StudentDemographic ||--o{ EducationOrganization : "has associated"
    StudentIdentificationCode ||--o{ Student : "has associated"
    StudentIdentificationCode ||--o{ EducationOrganization : "has associated"
    Student ||--o{ EducationOrganization : "has associated"
    StudentSchoolAssociation ||--o{ Student : "has associated"
    StudentSchoolAssociation ||--o{ School : "has associated"
    StudentSchoolAssociation ||--o{ GraduationPlan : "has associated"
    StudentEducationOrganizationAssociation ||--o{ Student : "has associated"
    StudentEducationOrganizationAssociation ||--o{ EducationOrganization : "has associated"
    StudentEducationOrganizationAssociation ||--o{ CrisisEvent : "has associated"
    StudentEducationOrganizationAssociation ||--o{ GraduationPlan : "has associated"
    StudentEducationOrganizationResponsibilityAssociation ||--o{ Student : "has associated"
    StudentEducationOrganizationResponsibilityAssociation ||--o{ EducationOrganization : "has associated"
    StudentTransportation ||--o{ Student : "has associated"
    StudentTransportation ||--o{ EducationOrganization : "has associated"
    GraduationPlan ||--o{ EducationOrganization : "has associated"
    AccountabilityRating ||--o{ EducationOrganization : "has associated"
    School ||--o{ EducationOrganization : "has associated"
    School ||--o{ LocalEducationAgency : "has associated"
    LocalEducationAgency ||--o{ EducationOrganization : "has associated"
    LocalEducationAgency ||--o{ LocalEducationAgency : "has associated"
