---
title: Graduation
config:
  layout: elk
---
erDiagram
    Student {
        string StudentUniqueId "I"
        common Name "R"
        common OtherName "OC"
        common BirthData "R"
        reference Person "O"
    }
    StudentSchoolAssociation {
        reference Student "I"
        reference School "I"
        bool PrimarySchool "O"
        enumeration SchoolYear "O"
        date EntryDate "I"
        descriptor EntryGradeLevel "R"
        descriptor EntryGradeLevelReason "O"
        descriptor EntryType "O"
        bool RepeatGradeIndicator "O"
        enumeration ClassOfSchoolYear "O"
        bool SchoolChoiceTransfer "O"
        date ExitWithdrawDate "O"
        descriptor ExitWithdrawType "O"
        descriptor EducationPlan "OC"
        descriptor ResidencyStatus "O"
        reference GraduationPlan "O"
        reference AlternativeGraduationPlan "OC"
        bool EmployedWhileEnrolled "O"
        reference Calendar "O"
        decimal FullTimeEquivalency "O"
        bool TermCompletionIndicator "O"
        reference NextYearSchool "O"
        descriptor NextYearGradeLevel "O"
        bool SchoolChoice "O"
        descriptor SchoolChoiceBasis "O"
        descriptor EnrollmentType "O"
    }
    StudentAcademicRecord {
        reference Student "I"
        reference EducationOrganization "I"
        enumeration SchoolYear "I"
        descriptor Term "I"
        common AcademicHonor "OC"
        common ClassRanking "O"
        common CumulativeAttemptedCredits "O"
        common CumulativeEarnedCredits "O"
        common SessionAttemptedCredits "O"
        common SessionEarnedCredits "O"
        common Diploma "OC"
        common GradePointAverage "OC"
        date ProjectedGraduationDate "O"
        common Recognition "OC"
        reference ReportCard "OC"
    }
    GraduationPlan {
        descriptor GraduationPlanType "I"
        bool IndividualPlan "O"
        common TotalRequiredCredits "R"
        common CreditsBySubject "OC"
        common CreditsByCourse "OC"
        common CreditsByCreditCategory "OC"
        reference EducationOrganization "I"
        enumeration GraduationSchoolYear "I"
        common RequiredAssessment "OC"
        common RequiredCertification "OC"
    }
    PostSecondaryEvent {
        date EventDate "I"
        descriptor PostSecondaryEventCategory "I"
        reference PostSecondaryInstitution "O"
        reference Student "I"
    }
    PostSecondaryInstitution {
        integer PostSecondaryInstitutionId "I"
        descriptor MediumOfInstruction "OC"
        descriptor PostSecondaryInstitutionLevel "O"
        descriptor AdministrativeFundingControl "O"
        descriptor FederalLocaleCode "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        string NameOfInstitution "R"
        string ShortNameOfInstitution "O"
        descriptor EducationOrganizationCategory "RC"
        common Address "OC"
        common InternationalAddress "OC"
        common InstitutionTelephone "OC"
        string WebSite "O"
        descriptor OperationalStatus "O"
        common EducationOrganizationIndicator "OC"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor CharterStatus "O"
        descriptor TitleIPartASchoolDesignation "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        descriptor AdministrativeFundingControl "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor FederalLocaleCode "O"
        reference PostSecondaryInstitution "O"
        bool ImprovingSchool "O"
        descriptor AccreditationStatus "O"
    }
    Student ||--o{ EducationOrganization : "has associated"
    Student ||--o{ School : "has associated"
    StudentSchoolAssociation ||--o{ GraduationPlan : "has associated"
    StudentAcademicRecord ||--o{ Student : "has associated"
    StudentAcademicRecord ||--o{ EducationOrganization : "has associated"
    GraduationPlan ||--o{ EducationOrganization : "has associated"
    PostSecondaryEvent ||--o{ Student : "has associated"
    PostSecondaryEvent ||--o{ StudentSchoolAssociation : "has associated"
    PostSecondaryEvent ||--o{ PostSecondaryInstitution : "has associated"
    PostSecondaryInstitution ||--o{ EducationOrganization : "has associated"
    School ||--o{ EducationOrganization : "has associated"
