---
title: RecruitmentAndStaffing
config:
  layout: elk
---
erDiagram
    ApplicantProfile {
        string ApplicantProfileIdentifier "I"
        common Name "R"
        descriptor Sex "O"
        string GenderIdentity "O"
        date BirthDate "O"
        common Address "OC"
        common InternationalAddress "OC"
        common Telephone "OC"
        common ElectronicMail "OC"
        bool HispanicLatinoEthnicity "O"
        descriptor Race "OC"
        common Citizenship "O"
        common Language "OC"
        common BackgroundCheck "OC"
        common Disability "OC"
        descriptor EconomicDisadvantage "O"
        bool FirstGenerationStudent "O"
        common ApplicantCharacteristic "OC"
        descriptor HighestCompletedLevelOfEducation "O"
        decimal YearsOfPriorProfessionalExperience "O"
        decimal YearsOfPriorTeachingExperience "O"
        bool HighlyQualifiedTeacher "O"
        descriptor HighlyQualifiedAcademicSubject "OC"
        common GradePointAverage "OC"
        string EducatorPreparationProgramName "OC"
    }
    Application {
        string ApplicationIdentifier "I"
        reference EducationOrganization "I"
        reference ApplicantProfile "I"
        date ApplicationDate "R"
        descriptor Term "OC"
        descriptor ApplicationStatus "R"
        bool CurrentEmployee "O"
        descriptor AcademicSubject "O"
        date AcceptedDate "O"
        descriptor ApplicationSource "O"
        date FirstContactDate "O"
        descriptor HighNeedsAcademicSubject "O"
        descriptor HireStatus "O"
        descriptor HiringSource "O"
        date WithdrawDate "O"
        descriptor WithdrawReason "O"
        common ScoreResult "OC"
        reference OpenStaffPosition "O"
        reference RecruitmentEventAttendance "OC"
    }
    ApplicationEvent {
        date EventDate "I"
        date EventEndDate "O"
        integer SequenceNumber "I"
        descriptor ApplicationEventType "I"
        decimal ApplicationEvaluationScore "O"
        descriptor ApplicationEventResult "O"
        reference Application "I"
        enumeration SchoolYear "R"
        descriptor Term "O"
    }
    OpenStaffPosition {
        descriptor EmploymentStatus "R"
        descriptor StaffClassification "R"
        string PositionTitle "O"
        string RequisitionNumber "I"
        descriptor ProgramAssignment "O"
        descriptor InstructionalGradeLevel "OC"
        descriptor AcademicSubject "OC"
        date DatePosted "R"
        date DatePostingRemoved "O"
        descriptor PostingResult "O"
        reference EducationOrganization "I"
        enumeration SchoolYear "O"
        decimal FullTimeEquivalency "O"
        descriptor OpenStaffPositionReason "O"
        bool IsActive "O"
        decimal MaxSalary "O"
        decimal MinSalary "O"
        descriptor FundingSource "O"
        bool HighNeedAcademicSubject "O"
        string PositionControlNumber "O"
        descriptor Term "O"
        decimal TotalBudgeted "O"
    }
    RecruitmentEvent {
        date EventDate "I"
        string EventDescription "O"
        string EventTitle "I"
        descriptor RecruitmentEventType "R"
        string EventLocation "O"
        reference EducationOrganization "I"
    }
    RecruitmentEventAttendance {
        string RecruitmentEventAttendeeIdentifier "I"
        bool Applied "O"
        common CurrentPosition "O"
        common Disability "OC"
        string ElectronicMailAddress "R"
        bool HispanicLatinoEthnicity "O"
        bool Met "O"
        common Name "R"
        string Notes "O"
        integer PreScreeningRating "O"
        common RecruitmentEventAttendeeQualifications "O"
        descriptor RecruitmentEventAttendeeType "O"
        descriptor Race "OC"
        reference RecruitmentEvent "I"
        bool Referral "O"
        string ReferredBy "O"
        descriptor Sex "O"
        string GenderIdentity "O"
        string SocialMediaNetworkName "O"
        string SocialMediaUserName "O"
        common Telephone "OC"
        common Touchpoint "OC"
    }
    ProfessionalDevelopmentEvent {
        string ProfessionalDevelopmentTitle "I"
        string Namespace "I"
        descriptor ProfessionalDevelopmentOfferedBy "R"
        integer TotalHours "O"
        bool Required "O"
        bool MultipleSession "O"
        string ProfessionalDevelopmentReason "O"
    }
    ProfessionalDevelopmentEventAttendance {
        reference Person "I"
        reference ProfessionalDevelopmentEvent "I"
        date AttendanceDate "I"
        descriptor AttendanceEventCategory "R"
        string AttendanceEventReason "O"
    }
    Person {
        string PersonId "I"
        descriptor SourceSystem "I"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        string NameOfInstitution "R"
        string ShortNameOfInstitution "O"
        descriptor EducationOrganizationCategory "RC"
        common Address "OC"
        common InternationalAddress "OC"
        common InstitutionTelephone "OC"
        string WebSite "O"
        descriptor OperationalStatus "O"
        common EducationOrganizationIndicator "OC"
    }
    Application ||--o{ ApplicantProfile : "has associated"
    Application ||--o{ EducationOrganization : "has associated"
    Application ||--o{ OpenStaffPosition : "has associated"
    Application ||--o{ RecruitmentEventAttendance : "has associated"
    ApplicationEvent ||--o{ Application : "has associated"
    RecruitmentEventAttendance ||--o{ RecruitmentEvent : "has associated"
    RecruitmentEventAttendance ||--o{ RecruitmentEventAttendance : "has associated"
    RecruitmentEvent ||--o{ EducationOrganization : "has associated"
    ProfessionalDevelopmentEvent ||--o{ ProfessionalDevelopmentEventAttendance : "has associated"
    ProfessionalDevelopmentEventAttendance ||--o{ Person : "has associated"
