---
title: Staff
config:
  layout: elk
---
erDiagram
    Staff {
        string StaffUniqueId "I"
        common Name "R"
        common OtherName "OC"
        date BirthDate "O"
        descriptor HighestCompletedLevelOfEducation "O"
        decimal YearsOfPriorProfessionalExperience "O"
        decimal YearsOfPriorTeachingExperience "O"
        string LoginId "O"
        bool HighlyQualifiedTeacher "O"
        common Recognition "OC"
        reference Credential "OC"
        reference Person "O"
        descriptor HighlyQualifiedAcademicSubject "OC"
        common EducatorResearch "O"
        reference EducatorPreparationProgram "OC"
        reference OpenStaffPosition "O"
    }
    StaffIdentificationCode {
        reference Staff "I"
        descriptor StaffIdentificationSystem "I"
        reference EducationOrganization "I"
        string IdentificationCode "R"
        string AssigningOrganizationIdentificationCode "O"
    }
    StaffDirectory {
        reference Staff "I"
        reference EducationOrganization "I"
        common Address "OC"
        common ElectronicMail "OC"
        common InternationalAddress "OC"
        common Telephone "OC"
    }
    StaffDemographic {
        reference Staff "I"
        reference EducationOrganization "I"
        descriptor AncestryEthnicOrigin "OC"
        common Citizenship "O"
        string GenderIdentity "O"
        bool HispanicLatinoEthnicity "O"
        common Language "OC"
        descriptor Race "OC"
        descriptor Sex "O"
        descriptor TribalAffiliation "OC"
    }
    Person {
        string PersonId "I"
        descriptor SourceSystem "I"
    }
    Credential {
        string CredentialIdentifier "I"
        descriptor StateOfIssueStateAbbreviation "I"
        string Namespace "R"
        descriptor CredentialType "R"
        date IssuanceDate "R"
        descriptor CredentialField "O"
        date EffectiveDate "O"
        date ExpirationDate "O"
        descriptor TeachingCredential "O"
        descriptor TeachingCredentialBasis "O"
        descriptor GradeLevel "OC"
        descriptor AcademicSubject "OC"
        string CredentialEndorsement "OC"
        string CertificationTitle "O"
        reference Certification "O"
        descriptor CertificationRoute "O"
        bool BoardCertificationIndicator "O"
        descriptor CredentialStatus "O"
        date CredentialStatusDate "O"
        reference Person "O"
        reference StudentAcademicRecord "OC"
        descriptor EducatorRole "O"
    }
    StaffAbsenceEvent {
        date EventDate "I"
        descriptor AbsenceEventCategory "I"
        string AbsenceEventReason "O"
        decimal HoursAbsent "O"
        reference Staff "I"
    }
    StaffLeave {
        date BeginDate "I"
        date EndDate "O"
        descriptor StaffLeaveEventCategory "I"
        string Reason "O"
        bool SubstituteAssigned "O"
        reference Staff "I"
    }
    StaffEducationOrganizationEmploymentAssociation {
        reference Staff "I"
        reference EducationOrganization "I"
        descriptor EmploymentStatus "I"
        common EmploymentPeriod "R"
        string Department "O"
        decimal FullTimeEquivalency "O"
        date OfferDate "O"
        currency HourlyWage "O"
        currency AnnualWage "O"
        reference Credential "O"
        common BackgroundCheck "OC"
        date ProbationCompleteDate "O"
        common Salary "O"
        descriptor LengthOfContract "O"
        common Seniority "OC"
        bool TenureTrack "O"
        bool Tenured "O"
    }
    StaffEducationOrganizationAssignmentAssociation {
        reference Staff "I"
        reference EducationOrganization "I"
        descriptor StaffClassification "I"
        string PositionTitle "O"
        date BeginDate "I"
        date EndDate "O"
        integer OrderOfAssignment "O"
        reference StaffEducationOrganizationEmploymentAssociation "O"
        reference Credential "O"
        decimal FullTimeEquivalency "O"
        decimal YearsOfExperienceAtCurrentEducationOrganization "O"
    }
    StaffSchoolAssociation {
        reference Staff "I"
        reference School "I"
        enumeration SchoolYear "O"
        descriptor ProgramAssignment "I"
        descriptor GradeLevel "OC"
        descriptor AcademicSubject "OC"
        reference Calendar "O"
    }
    OpenStaffPosition {
        descriptor EmploymentStatus "R"
        descriptor StaffClassification "R"
        string PositionTitle "O"
        string RequisitionNumber "I"
        descriptor ProgramAssignment "O"
        descriptor InstructionalGradeLevel "OC"
        descriptor AcademicSubject "OC"
        date DatePosted "R"
        date DatePostingRemoved "O"
        descriptor PostingResult "O"
        reference EducationOrganization "I"
        enumeration SchoolYear "O"
        decimal FullTimeEquivalency "O"
        descriptor OpenStaffPositionReason "O"
        bool IsActive "O"
        decimal MaxSalary "O"
        decimal MinSalary "O"
        descriptor FundingSource "O"
        bool HighNeedAcademicSubject "O"
        string PositionControlNumber "O"
        descriptor Term "O"
        decimal TotalBudgeted "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        string NameOfInstitution "R"
        string ShortNameOfInstitution "O"
        descriptor EducationOrganizationCategory "RC"
        common Address "OC"
        common InternationalAddress "OC"
        common InstitutionTelephone "OC"
        string WebSite "O"
        descriptor OperationalStatus "O"
        common EducationOrganizationIndicator "OC"
    }
    EducationServiceCenter {
        integer EducationServiceCenterId "I"
        reference StateEducationAgency "O"
    }
    LocalEducationAgency {
        integer LocalEducationAgencyId "I"
        descriptor LocalEducationAgencyCategory "R"
        descriptor CharterStatus "O"
        common LocalEducationAgencyAccountability "OC"
        common LocalEducationAgencyFederalFunds "OC"
        reference ParentLocalEducationAgency "O"
        reference EducationServiceCenter "O"
        reference StateEducationAgency "O"
        descriptor FederalLocaleCode "O"
    }
    StateEducationAgency {
        integer StateEducationAgencyId "I"
        common StateEducationAgencyAccountability "OC"
        common StateEducationAgencyFederalFunds "OC"
        descriptor FederalLocaleCode "O"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor CharterStatus "O"
        descriptor TitleIPartASchoolDesignation "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        descriptor AdministrativeFundingControl "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor FederalLocaleCode "O"
        reference PostSecondaryInstitution "O"
        bool ImprovingSchool "O"
        descriptor AccreditationStatus "O"
    }
    Staff ||--o{ Person : "has associated"
    Staff ||--o{ Credential : "has associated"
    Staff ||--o{ School : "has associated"
    Staff ||--o{ EducationOrganization : "has associated"
    StaffIdentificationCode ||--o{ Staff : "has associated"
    StaffDirectory ||--o{ Staff : "has associated"
    StaffDirectory ||--o{ EducationOrganization : "has associated"
    StaffDemographic ||--o{ Staff : "has associated"
    StaffAbsenceEvent ||--o{ Staff : "has associated"
    StaffLeave ||--o{ Staff : "has associated"
    StaffEducationOrganizationEmploymentAssociation ||--o{ StaffLeave : "has associated"
    StaffEducationOrganizationAssignmentAssociation ||--o{ StaffEducationOrganizationEmploymentAssociation : "has associated"
    StaffEducationOrganizationAssignmentAssociation ||--o{ Credential : "has associated"
    EducationOrganization ||--o{ StaffDirectory : "has associated"
    EducationOrganization ||--o{ StaffIdentificationCode : "has associated"
    EducationOrganization ||--o{ StaffDemographic : "has associated"
    OpenStaffPosition ||--o{ EducationOrganization : "has associated"
    School ||--o{ EducationOrganization : "has associated"
    School ||--o{ LocalEducationAgency : "has associated"
    LocalEducationAgency ||--o{ EducationOrganization : "has associated"
    LocalEducationAgency ||--o{ EducationServiceCenter : "has associated"
    LocalEducationAgency ||--o{ StateEducationAgency : "has associated"
    LocalEducationAgency ||--o{ LocalEducationAgency : "has associated"
    EducationServiceCenter ||--o{ EducationOrganization : "has associated"
    EducationServiceCenter ||--o{ StateEducationAgency : "has associated"
    StateEducationAgency ||--o{ EducationOrganization : "has associated"
