---
title: StudentAcademicRecord
config:
  layout: elk
---
erDiagram
    Student {
        string StudentUniqueId "I"
        common Name "R"
        common OtherName "OC"
        common BirthData "R"
        reference Person "O"
    }
    StudentAcademicRecord {
        reference Student "I"
        reference EducationOrganization "I"
        enumeration SchoolYear "I"
        descriptor Term "I"
        common AcademicHonor "OC"
        common ClassRanking "O"
        common CumulativeAttemptedCredits "O"
        common CumulativeEarnedCredits "O"
        common SessionAttemptedCredits "O"
        common SessionEarnedCredits "O"
        common Diploma "OC"
        common GradePointAverage "OC"
        date ProjectedGraduationDate "O"
        common Recognition "OC"
        reference ReportCard "OC"
    }
    CourseTranscript {
        descriptor CourseAttemptResult "I"
        common AttemptedCredits "O"
        common EarnedCredits "O"
        common EarnedAdditionalCredits "OC"
        descriptor WhenTakenGradeLevel "O"
        descriptor MethodCreditEarned "O"
        string FinalLetterGradeEarned "O"
        decimal FinalNumericGradeEarned "O"
        descriptor CourseRepeatCode "O"
        reference Course "I"
        reference StudentAcademicRecord "I"
        reference Section "OC"
        reference ResponsibleTeacherStaff "O"
        reference CourseProgram "OC"
        string CourseTitle "O"
        string AlternativeCourseTitle "O"
        reference ExternalEducationOrganization "O"
        string ExternalEducationOrganizationNameOfInstitution "O"
        common AlternativeCourseIdentificationCode "OC"
        string AssigningOrganizationIdentificationCode "O"
        string CourseCatalogURL "O"
        descriptor CreditCategory "OC"
        descriptor AcademicSubject "OC"
        common PartialCourseTranscriptAwards "OC"
    }
    ReportCard {
        reference Grade "OC"
        reference StudentCompetencyObjective "OC"
        common GradePointAverage "OC"
        decimal NumberOfDaysAbsent "O"
        decimal NumberOfDaysInAttendance "O"
        integer NumberOfDaysTardy "O"
        reference Student "I"
        reference EducationOrganization "I"
        reference GradingPeriod "I"
    }
    Grade {
        string LetterGradeEarned "O"
        decimal NumericGradeEarned "O"
        string DiagnosticStatement "O"
        descriptor GradeType "I"
        descriptor PerformanceBaseConversion "O"
        reference StudentSectionAssociation "I"
        reference GradingPeriod "I"
        common LearningStandardGrade "OC"
        bool CurrentGradeIndicator "O"
        date CurrentGradeAsOfDate "O"
        string GradeEarnedDescription "O"
    }
    StudentCompetencyObjective {
        reference CompetencyObjective "I"
        descriptor CompetencyLevel "R"
        string DiagnosticStatement "O"
        reference GradingPeriod "I"
        reference Student "I"
        choice StudentCompetencyObjectiveSectionOrProgramChoice "O"
    }
    StudentSectionAssociation {
        reference Student "I"
        reference Section "I"
        date BeginDate "I"
        date EndDate "O"
        bool HomeroomIndicator "O"
        descriptor RepeatIdentifier "O"
        bool TeacherStudentDataLinkExclusion "O"
        descriptor AttemptStatus "O"
        reference Program "OC"
        common DualCredit "O"
    }
    GeneralStudentProgramAssociation {
        reference Student "I"
        reference Program "I"
        date BeginDate "I"
        date EndDate "O"
        descriptor ReasonExited "O"
        reference EducationOrganization "I"
        bool ServedOutsideOfRegularSession "O"
        common ProgramParticipationStatus "OC"
    }
    GradebookEntry {
        string GradebookEntryIdentifier "I"
        string Namespace "I"
        string SourceSectionIdentifier "R"
        reference Section "O"
        date DateAssigned "R"
        string Title "R"
        string Description "O"
        date DueDate "O"
        time DueTime "O"
        descriptor GradebookEntryType "O"
        decimal MaxPoints "O"
        reference GradingPeriod "O"
        reference LearningStandard "OC"
    }
    StudentGradebookEntry {
        reference GradebookEntry "I"
        reference Student "I"
        descriptor CompetencyLevel "O"
        date DateFulfilled "O"
        time TimeFulfilled "O"
        string DiagnosticStatement "O"
        decimal PointsEarned "O"
        string LetterGradeEarned "O"
        decimal NumericGradeEarned "O"
        descriptor SubmissionStatus "O"
        descriptor AssignmentLateStatus "O"
        date DateCompleted "O"
        bool AssignmentPassed "O"
    }
    CompetencyObjective {
        string CompetencyObjectiveId "O"
        string Objective "I"
        string Description "O"
        descriptor ObjectiveGradeLevel "I"
        reference EducationOrganization "I"
        string SuccessCriteria "O"
    }
    Course {
        string CourseCode "I"
        string CourseTitle "R"
        integer NumberOfParts "R"
        common CourseIdentificationCode "RC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor OfferedGradeLevel "OC"
        descriptor AcademicSubject "OC"
        string CourseDescription "O"
        integer TimeRequiredForCompletion "O"
        date DateCourseAdopted "O"
        bool HighSchoolCourseRequirement "O"
        descriptor CourseGPAApplicability "O"
        descriptor CourseDefinedBy "O"
        common MinimumAvailableCredits "O"
        common MaximumAvailableCredits "O"
        descriptor CareerPathway "O"
        descriptor CompetencyLevel "OC"
        reference EducationOrganization "I"
        reference LearningStandard "OC"
        integer MaxCompletionsForCredit "O"
    }
    CourseOffering {
        string LocalCourseCode "I"
        string LocalCourseTitle "O"
        integer InstructionalTimePlanned "O"
        descriptor CurriculumUsed "OC"
        reference School "I"
        reference Session "I"
        reference Course "R"
        descriptor CourseLevelCharacteristic "OC"
        descriptor OfferedGradeLevel "OC"
    }
    Section {
        string SectionIdentifier "I"
        descriptor SectionType "O"
        integer SequenceOfCourse "O"
        descriptor EducationalEnvironment "O"
        descriptor MediumOfInstruction "O"
        descriptor PopulationServed "O"
        common AvailableCredits "O"
        descriptor SectionCharacteristic "OC"
        descriptor InstructionLanguage "O"
        reference CourseOffering "I"
        reference LocationSchool "O"
        reference Location "O"
        reference ClassPeriod "OC"
        reference Program "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor OfferedGradeLevel "OC"
        bool OfficialAttendancePeriod "O"
        string SectionName "O"
    }
    Program {
        reference EducationOrganization "I"
        string ProgramId "O"
        string ProgramName "I"
        descriptor ProgramType "I"
        descriptor ProgramCharacteristic "OC"
        descriptor ProgramSponsor "OC"
        reference LearningStandard "OC"
    }
    GradingPeriod {
        reference School "I"
        descriptor GradingPeriod "I"
        string GradingPeriodName "I"
        integer PeriodSequence "O"
        enumeration SchoolYear "I"
        date BeginDate "R"
        date EndDate "R"
        integer TotalInstructionalDays "R"
    }
    Session {
        string SessionName "I"
        enumeration SchoolYear "I"
        date BeginDate "R"
        date EndDate "R"
        descriptor Term "R"
        integer TotalInstructionalDays "R"
        reference School "I"
        reference GradingPeriod "OC"
        reference AcademicWeek "OC"
    }
    LearningStandard {
        string LearningStandardId "I"
        common LearningStandardIdentificationCode "OC"
        string Description "R"
        string LearningStandardItemCode "O"
        common ContentStandard "R"
        string URI "O"
        descriptor GradeLevel "RC"
        descriptor AcademicSubject "RC"
        string CourseTitle "O"
        string SuccessCriteria "O"
        reference ParentLearningStandard "O"
        string Namespace "R"
        descriptor LearningStandardCategory "O"
        descriptor LearningStandardScope "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        string NameOfInstitution "R"
        string ShortNameOfInstitution "O"
        descriptor EducationOrganizationCategory "RC"
        common Address "OC"
        common InternationalAddress "OC"
        common InstitutionTelephone "OC"
        string WebSite "O"
        descriptor OperationalStatus "O"
        common EducationOrganizationIndicator "OC"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor CharterStatus "O"
        descriptor TitleIPartASchoolDesignation "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        descriptor AdministrativeFundingControl "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor FederalLocaleCode "O"
        reference PostSecondaryInstitution "O"
        bool ImprovingSchool "O"
        descriptor AccreditationStatus "O"
    }
    EducationOrganization ||--o{ Program : "IsDirectProviderOf"
    Course }o--|| EducationOrganization : "HasAssociated"
    Session }o--|| School : "HasAssociated"
    CompetencyObjective }o--|| EducationOrganization : "HasAssociated"
    LearningStandard }o--o| LearningStandard : "HasFunctional Component"
    StudentAcademicRecord }o--|| EducationOrganization : "HasAssociated"
    StudentAcademicRecord }o--|| Student : "HasAssociated"
    ReportCard }o--|| Student : "HasAssociated"
    ReportCard ||--o{ Grade : "HasFunctionalComponent"
    ReportCard }o--o{ StudentCompetencyObjective : "HasAssociated"
    ReportCard }o--|| GradingPeriod : "HasAssociated"
    ReportCard }o--|| EducationOrganization : "HasAssociated"
    StudentCompetencyObjective }o--|| GradingPeriod : "HasAssociated"
    StudentCompetencyObjective }o--o{ StudentSectionAssociation : "HasAssociated"
    StudentCompetencyObjective }o--o{ GeneralStudentProgramAssociation : "HasAssociated"
    StudentCompetencyObjective }o--|| CompetencyObjective : "HasAssociated"
    Program }o--o{ EducationOrganization : "HasAssociated"
    Program }o--o{ LearningStandard : "HasAssociated"
    GeneralStudentProgramAssociation }o--|| EducationOrganization : "HasAssociated"
    GradebookEntry }o--o| GradingPeriod : "HasAssociated"
    GradebookEntry }o--|| Section : "HasAssociated"
    CourseOffering }o--|| Session : "HasAssociated"
    CourseOffering }o--|| School : "HasAssociated"
    Grade }o--|| GradingPeriod : "HasAssociated"
    Grade }o--|| StudentSectionAssociation : "HasAssociated"
    StudentGradebookEntry }o--|| GradebookEntry : "HasAssociated"
    StudentGradebookEntry }o--|| StudentSectionAssociation : "HasAssociated"
    CourseTranscript }o--|| StudentAcademicRecord : "HasAssociated"
    CourseTranscript }o--|| Course : "HasAssociated"
    Section }o--o{ Program : "HasAssociated"
    Section }|--o| School : "HasAssociated"
    Student }o--o{ School : "HasAssociated"
    Student }o--o{ Section : "ParticipatesIn"
    StudentCompetencyObjective }o--|| Student : "HasAssociated"
    Section }o--|| CourseOffering : "HasAssociated"
    GradebookEntry }o--o{ LearningStandard : "HasAssociated"
    CourseOffering }o--|| Course : "HasAssociated"
    Course }o--o{ LearningStandard : "HasAssociated"
    Session }|--o{ GradingPeriod : "HasAssociated"
    CourseTranscript }o--o| EducationOrganization : "HasAssociatedExternal"
    GradingPeriod }o--|| School : "HasAssociated"
    Student }o--o{ Program : "ParticipatesIn"
    LearningStandard }o--o| LearningStandard : "HasFunctionalComponent"
    LearningStandard }o--o{ LearningStandard : "HasAssociatedPrerequisite"
    Grade }o--o{ LearningStandard : "HasAssociated"
    LearningStandard }o--o{ LearningStandard : "HasAssociatedEquivalence"
    StudentAcademicRecord ||--o{ ReportCard : "HasFunctionalComponent"
