---
title: StudentAcademicRecord-ReportCard
config:
  layout: elk
---
erDiagram
    Student {
        string StudentUniqueId "I"
        common Name "R"
        common OtherName "OC"
        common BirthData "R"
        reference Person "O"
    }
    ReportCard {
        reference Grade "OC"
        reference StudentCompetencyObjective "OC"
        common GradePointAverage "OC"
        decimal NumberOfDaysAbsent "O"
        decimal NumberOfDaysInAttendance "O"
        integer NumberOfDaysTardy "O"
        reference Student "I"
        reference EducationOrganization "I"
        reference GradingPeriod "I"
    }
    Grade {
        string LetterGradeEarned "O"
        decimal NumericGradeEarned "O"
        string DiagnosticStatement "O"
        descriptor GradeType "I"
        descriptor PerformanceBaseConversion "O"
        reference StudentSectionAssociation "I"
        reference GradingPeriod "I"
        common LearningStandardGrade "OC"
        bool CurrentGradeIndicator "O"
        date CurrentGradeAsOfDate "O"
        string GradeEarnedDescription "O"
    }
    StudentCompetencyObjective {
        reference CompetencyObjective "I"
        descriptor CompetencyLevel "R"
        string DiagnosticStatement "O"
        reference GradingPeriod "I"
        reference Student "I"
        choice StudentCompetencyObjectiveSectionOrProgramChoice "O"
    }
    StudentSectionAssociation {
        reference Student "I"
        reference Section "I"
        date BeginDate "I"
        date EndDate "O"
        bool HomeroomIndicator "O"
        descriptor RepeatIdentifier "O"
        bool TeacherStudentDataLinkExclusion "O"
        descriptor AttemptStatus "O"
        reference Program "OC"
        common DualCredit "O"
    }
    GeneralStudentProgramAssociation {
        reference Student "I"
        reference Program "I"
        date BeginDate "I"
        date EndDate "O"
        descriptor ReasonExited "O"
        reference EducationOrganization "I"
        bool ServedOutsideOfRegularSession "O"
        common ProgramParticipationStatus "OC"
    }
    GradingPeriod {
        reference School "I"
        descriptor GradingPeriod "I"
        string GradingPeriodName "I"
        integer PeriodSequence "O"
        enumeration SchoolYear "I"
        date BeginDate "R"
        date EndDate "R"
        integer TotalInstructionalDays "R"
    }
    CompetencyObjective {
        string CompetencyObjectiveId "O"
        string Objective "I"
        string Description "O"
        descriptor ObjectiveGradeLevel "I"
        reference EducationOrganization "I"
        string SuccessCriteria "O"
    }
    Section {
        string SectionIdentifier "I"
        descriptor SectionType "O"
        integer SequenceOfCourse "O"
        descriptor EducationalEnvironment "O"
        descriptor MediumOfInstruction "O"
        descriptor PopulationServed "O"
        common AvailableCredits "O"
        descriptor SectionCharacteristic "OC"
        descriptor InstructionLanguage "O"
        reference CourseOffering "I"
        reference LocationSchool "O"
        reference Location "O"
        reference ClassPeriod "OC"
        reference Program "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor OfferedGradeLevel "OC"
        bool OfficialAttendancePeriod "O"
        string SectionName "O"
    }
    Program {
        reference EducationOrganization "I"
        string ProgramId "O"
        string ProgramName "I"
        descriptor ProgramType "I"
        descriptor ProgramCharacteristic "OC"
        descriptor ProgramSponsor "OC"
        reference LearningStandard "OC"
    }
    LearningStandard {
        string LearningStandardId "I"
        common LearningStandardIdentificationCode "OC"
        string Description "R"
        string LearningStandardItemCode "O"
        common ContentStandard "R"
        string URI "O"
        descriptor GradeLevel "RC"
        descriptor AcademicSubject "RC"
        string CourseTitle "O"
        string SuccessCriteria "O"
        reference ParentLearningStandard "O"
        string Namespace "R"
        descriptor LearningStandardCategory "O"
        descriptor LearningStandardScope "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        string NameOfInstitution "R"
        string ShortNameOfInstitution "O"
        descriptor EducationOrganizationCategory "RC"
        common Address "OC"
        common InternationalAddress "OC"
        common InstitutionTelephone "OC"
        string WebSite "O"
        descriptor OperationalStatus "O"
        common EducationOrganizationIndicator "OC"
    }
    ReportCard ||--o{ Student : "has associated"
    ReportCard ||--o{ GradingPeriod : "has associated"
    ReportCard ||--o{ EducationOrganization : "has associated"
    ReportCard ||--o{ Grade : "has associated"
    ReportCard ||--o{ StudentCompetencyObjective : "has associated"
    Grade ||--o{ GradingPeriod : "has associated"
    Grade ||--o{ StudentSectionAssociation : "has associated"
    Grade ||--o{ LearningStandard : "has associated"
    StudentCompetencyObjective ||--o{ Student : "has associated"
    StudentCompetencyObjective ||--o{ GradingPeriod : "has associated"
    StudentCompetencyObjective ||--o{ CompetencyObjective : "has associated"
    StudentCompetencyObjective ||--o{ GeneralStudentProgramAssociation : "has associated"
    StudentCompetencyObjective ||--o{ StudentSectionAssociation : "has associated"
    StudentSectionAssociation ||--o{ Student : "has associated"
    GeneralStudentProgramAssociation ||--o{ EducationOrganization : "has associated"
    GeneralStudentProgramAssociation ||--o{ StudentSectionAssociation : "has associated"
    Student ||--o{ Section : "has associated"
    Student ||--o{ Program : "has associated"
    Section ||--o{ Program : "has associated"
    Program ||--o{ EducationOrganization : "has associated"
    CompetencyObjective ||--o{ EducationOrganization : "has associated"
    LearningStandard ||--o{ LearningStandard : "has associated"
