---
title: StudentAttendance
config:
  layout: elk
---
erDiagram
    Student {
        string StudentUniqueId "I"
        common Name "R"
        common OtherName "OC"
        common BirthData "R"
        reference Person "O"
    }
    StudentSchoolAttendanceEvent {
        common AttendanceEvent "R"
        reference Student "I"
        reference School "I"
        reference Session "I"
        integer SchoolAttendanceDuration "O"
        time ArrivalTime "O"
        time DepartureTime "O"
    }
    StudentSectionAttendanceEvent {
        common AttendanceEvent "R"
        reference Student "I"
        reference Section "I"
        integer SectionAttendanceDuration "O"
        time ArrivalTime "O"
        time DepartureTime "O"
        reference ClassPeriod "OC"
    }
    StudentProgramAttendanceEvent {
        common AttendanceEvent "R"
        reference Student "I"
        reference EducationOrganization "I"
        reference Program "I"
        integer ProgramAttendanceDuration "O"
    }
    StudentSectionAssociation {
        reference Student "I"
        reference Section "I"
        date BeginDate "I"
        date EndDate "O"
        bool HomeroomIndicator "O"
        descriptor RepeatIdentifier "O"
        bool TeacherStudentDataLinkExclusion "O"
        descriptor AttemptStatus "O"
        reference Program "OC"
        common DualCredit "O"
    }
    GeneralStudentProgramAssociation {
        reference Student "I"
        reference Program "I"
        date BeginDate "I"
        date EndDate "O"
        descriptor ReasonExited "O"
        reference EducationOrganization "I"
        bool ServedOutsideOfRegularSession "O"
        common ProgramParticipationStatus "OC"
    }
    SectionAttendanceTakenEvent {
        reference Section "I"
        reference CalendarDate "I"
        date EventDate "R"
        reference Staff "O"
    }
    Session {
        string SessionName "I"
        enumeration SchoolYear "I"
        date BeginDate "R"
        date EndDate "R"
        descriptor Term "R"
        integer TotalInstructionalDays "R"
        reference School "I"
        reference GradingPeriod "OC"
        reference AcademicWeek "OC"
    }
    Section {
        string SectionIdentifier "I"
        descriptor SectionType "O"
        integer SequenceOfCourse "O"
        descriptor EducationalEnvironment "O"
        descriptor MediumOfInstruction "O"
        descriptor PopulationServed "O"
        common AvailableCredits "O"
        descriptor SectionCharacteristic "OC"
        descriptor InstructionLanguage "O"
        reference CourseOffering "I"
        reference LocationSchool "O"
        reference Location "O"
        reference ClassPeriod "OC"
        reference Program "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor OfferedGradeLevel "OC"
        bool OfficialAttendancePeriod "O"
        string SectionName "O"
    }
    Program {
        reference EducationOrganization "I"
        string ProgramId "O"
        string ProgramName "I"
        descriptor ProgramType "I"
        descriptor ProgramCharacteristic "OC"
        descriptor ProgramSponsor "OC"
        reference LearningStandard "OC"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor CharterStatus "O"
        descriptor TitleIPartASchoolDesignation "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        descriptor AdministrativeFundingControl "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor FederalLocaleCode "O"
        reference PostSecondaryInstitution "O"
        bool ImprovingSchool "O"
        descriptor AccreditationStatus "O"
    }
    Staff {
        string StaffUniqueId "I"
        common Name "R"
        common OtherName "OC"
        date BirthDate "O"
        descriptor HighestCompletedLevelOfEducation "O"
        decimal YearsOfPriorProfessionalExperience "O"
        decimal YearsOfPriorTeachingExperience "O"
        string LoginId "O"
        bool HighlyQualifiedTeacher "O"
        common Recognition "OC"
        reference Credential "OC"
        reference Person "O"
        descriptor HighlyQualifiedAcademicSubject "OC"
        common EducatorResearch "O"
        reference EducatorPreparationProgram "OC"
        reference OpenStaffPosition "O"
    }
    StudentSchoolAttendanceEvent ||--o{ Student : "has associated"
    StudentSchoolAttendanceEvent ||--o{ School : "has associated"
    StudentSchoolAttendanceEvent ||--o{ Session : "has associated"
    StudentSectionAttendanceEvent ||--o{ Student : "has associated"
    StudentSectionAttendanceEvent ||--o{ Section : "has associated"
    StudentSectionAttendanceEvent ||--o{ StudentSectionAssociation : "has associated"
    StudentProgramAttendanceEvent ||--o{ Student : "has associated"
    StudentProgramAttendanceEvent ||--o{ Program : "has associated"
    SectionAttendanceTakenEvent ||--o{ Section : "has associated"
    SectionAttendanceTakenEvent ||--o{ Staff : "has associated"
    Student ||--o{ School : "has associated"
    Student ||--o{ Section : "has associated"
    Student ||--o{ Program : "has associated"
    Session ||--o{ School : "has associated"
    Section ||--o{ School : "has associated"
    Section ||--o{ Program : "has associated"
    Program ||--o{ Staff : "has associated"
    Staff ||--o{ School : "has associated"
    Staff ||--o{ Section : "has associated"
