---
title: StudentCohort
config:
  layout: elk
---
erDiagram
    Student {
        string StudentUniqueId "I"
        common Name "R"
        common OtherName "OC"
        common BirthData "R"
        reference Person "O"
    }
    Staff {
        string StaffUniqueId "I"
        common Name "R"
        common OtherName "OC"
        date BirthDate "O"
        descriptor HighestCompletedLevelOfEducation "O"
        decimal YearsOfPriorProfessionalExperience "O"
        decimal YearsOfPriorTeachingExperience "O"
        string LoginId "O"
        bool HighlyQualifiedTeacher "O"
        common Recognition "OC"
        reference Credential "OC"
        reference Person "O"
        descriptor HighlyQualifiedAcademicSubject "OC"
        common EducatorResearch "O"
        reference EducatorPreparationProgram "OC"
        reference OpenStaffPosition "O"
    }
    Cohort {
        string CohortIdentifier "I"
        string CohortDescription "O"
        descriptor CohortType "R"
        descriptor CohortScope "O"
        descriptor AcademicSubject "O"
        reference EducationOrganization "I"
        reference Program "OC"
    }
    StudentCohortAssociation {
        reference Student "I"
        reference Cohort "I"
        date BeginDate "I"
        date EndDate "O"
        reference Section "OC"
    }
    StaffCohortAssociation {
        reference Staff "I"
        reference Cohort "I"
        date BeginDate "I"
        date EndDate "O"
        bool StudentRecordAccess "O"
    }
    StudentInterventionAssociation {
        reference Student "I"
        reference Intervention "I"
        reference Cohort "O"
        common InterventionEffectiveness "OC"
        string DiagnosticStatement "O"
        integer Dosage "O"
    }
    Intervention {
        common EducationContentSource "R"
        descriptor InterventionClass "R"
        descriptor Diagnosis "OC"
        descriptor PopulationServed "OC"
        descriptor AppropriateSex "OC"
        descriptor AppropriateGradeLevel "OC"
        descriptor DeliveryMethod "R"
        reference InterventionPrescription "OC"
        date BeginDate "R"
        date EndDate "O"
        common MeetingTime "OC"
        reference Staff "OC"
        reference EducationOrganization "I"
        string InterventionIdentificationCode "I"
        integer MinDosage "O"
        integer MaxDosage "O"
        string Namespace "O"
    }
    StudentSectionAssociation {
        reference Student "I"
        reference Section "I"
        date BeginDate "I"
        date EndDate "O"
        bool HomeroomIndicator "O"
        descriptor RepeatIdentifier "O"
        bool TeacherStudentDataLinkExclusion "O"
        descriptor AttemptStatus "O"
        reference Program "OC"
        common DualCredit "O"
    }
    StaffSectionAssociation {
        reference Staff "I"
        reference Section "I"
        descriptor ClassroomPosition "R"
        date BeginDate "I"
        date EndDate "O"
        bool HighlyQualifiedTeacher "O"
        bool TeacherStudentDataLinkExclusion "O"
        percent PercentageContribution "O"
    }
    Program {
        reference EducationOrganization "I"
        string ProgramId "O"
        string ProgramName "I"
        descriptor ProgramType "I"
        descriptor ProgramCharacteristic "OC"
        descriptor ProgramSponsor "OC"
        reference LearningStandard "OC"
    }
    Section {
        string SectionIdentifier "I"
        descriptor SectionType "O"
        integer SequenceOfCourse "O"
        descriptor EducationalEnvironment "O"
        descriptor MediumOfInstruction "O"
        descriptor PopulationServed "O"
        common AvailableCredits "O"
        descriptor SectionCharacteristic "OC"
        descriptor InstructionLanguage "O"
        reference CourseOffering "I"
        reference LocationSchool "O"
        reference Location "O"
        reference ClassPeriod "OC"
        reference Program "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor OfferedGradeLevel "OC"
        bool OfficialAttendancePeriod "O"
        string SectionName "O"
    }
    EducationOrganization {
        integer EducationOrganizationId "I"
        string NameOfInstitution "R"
        string ShortNameOfInstitution "O"
        descriptor EducationOrganizationCategory "RC"
        common Address "OC"
        common InternationalAddress "OC"
        common InstitutionTelephone "OC"
        string WebSite "O"
        descriptor OperationalStatus "O"
        common EducationOrganizationIndicator "OC"
    }
    Cohort ||--o{ Student : "has associated"
    Cohort ||--o{ Program : "has associated"
    Cohort ||--o{ EducationOrganization : "has associated"
    Cohort ||--o{ Staff : "has associated"
    StudentCohortAssociation ||--o{ StudentCohortAssociation : "has associated"
    StudentCohortAssociation ||--o{ Section : "has associated"
    StaffCohortAssociation ||--o{ StaffCohortAssociation : "has associated"
    StudentInterventionAssociation ||--o{ Cohort : "has associated"
    StudentInterventionAssociation ||--o{ Student : "has associated"
    StudentSectionAssociation ||--o{ StudentSectionAssociation : "has associated"
    StaffSectionAssociation ||--o{ Section : "has associated"
    Student ||--o{ Intervention : "has associated"
    Student ||--o{ Program : "has associated"
    Student ||--o{ Section : "has associated"
    Staff ||--o{ EducationOrganization : "has associated"
    Staff ||--o{ Section : "has associated"
    Intervention ||--o{ EducationOrganization : "has associated"
    Intervention ||--o{ Staff : "has associated"
    Program ||--o{ EducationOrganization : "has associated"
    Program ||--o{ Staff : "has associated"
    EducationOrganization ||--o{ Program : "has associated"
    Section ||--o{ Program : "has associated"
