---
title: StudentAcademicRecord-Gradebook
config:
  layout: elk
---
erDiagram
    Course {
        string CourseCode "I"
        string CourseTitle "R"
        integer NumberOfParts "R"
        common CourseIdentificationCode "RC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor OfferedGradeLevel "OC"
        descriptor AcademicSubject "OC"
        string CourseDescription "O"
        integer TimeRequiredForCompletion "O"
        date DateCourseAdopted "O"
        bool HighSchoolCourseRequirement "O"
        descriptor CourseGPAApplicability "O"
        descriptor CourseDefinedBy "O"
        common MinimumAvailableCredits "O"
        common MaximumAvailableCredits "O"
        descriptor CareerPathway "O"
        descriptor CompetencyLevel "OC"
        reference EducationOrganization "I"
        reference LearningStandard "OC"
        integer MaxCompletionsForCredit "O"
    }
    LearningStandard {
        string LearningStandardId "I"
        common LearningStandardIdentificationCode "OC"
        string Description "R"
        string LearningStandardItemCode "O"
        common ContentStandard "R"
        string URI "O"
        descriptor GradeLevel "RC"
        descriptor AcademicSubject "RC"
        string CourseTitle "O"
        string SuccessCriteria "O"
        reference ParentLearningStandard "O"
        string Namespace "R"
        descriptor LearningStandardCategory "O"
        descriptor LearningStandardScope "O"
    }
    GradebookEntry {
        string GradebookEntryIdentifier "I"
        string Namespace "I"
        string SourceSectionIdentifier "R"
        reference Section "O"
        date DateAssigned "R"
        string Title "R"
        string Description "O"
        date DueDate "O"
        time DueTime "O"
        descriptor GradebookEntryType "O"
        decimal MaxPoints "O"
        reference GradingPeriod "O"
        reference LearningStandard "OC"
    }
    StudentGradebookEntry {
        reference GradebookEntry "I"
        reference Student "I"
        descriptor CompetencyLevel "O"
        date DateFulfilled "O"
        time TimeFulfilled "O"
        string DiagnosticStatement "O"
        decimal PointsEarned "O"
        string LetterGradeEarned "O"
        decimal NumericGradeEarned "O"
        descriptor SubmissionStatus "O"
        descriptor AssignmentLateStatus "O"
        date DateCompleted "O"
        bool AssignmentPassed "O"
    }
    StudentSectionAssociation {
        reference Student "I"
        reference Section "I"
        date BeginDate "I"
        date EndDate "O"
        bool HomeroomIndicator "O"
        descriptor RepeatIdentifier "O"
        bool TeacherStudentDataLinkExclusion "O"
        descriptor AttemptStatus "O"
        reference Program "OC"
        common DualCredit "O"
    }
    Section {
        string SectionIdentifier "I"
        descriptor SectionType "O"
        integer SequenceOfCourse "O"
        descriptor EducationalEnvironment "O"
        descriptor MediumOfInstruction "O"
        descriptor PopulationServed "O"
        common AvailableCredits "O"
        descriptor SectionCharacteristic "OC"
        descriptor InstructionLanguage "O"
        reference CourseOffering "I"
        reference LocationSchool "O"
        reference Location "O"
        reference ClassPeriod "OC"
        reference Program "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor OfferedGradeLevel "OC"
        bool OfficialAttendancePeriod "O"
        string SectionName "O"
    }
    Student {
        string StudentUniqueId "I"
        common Name "R"
        common OtherName "OC"
        common BirthData "R"
        reference Person "O"
    }
    Course ||--o{ LearningStandard : "has associated"
    LearningStandard ||--o{ LearningStandard : "has associated"
    GradebookEntry ||--o{ LearningStandard : "has associated"
    GradebookEntry ||--o{ Section : "has associated"
    StudentGradebookEntry ||--o{ GradebookEntry : "has associated"
    StudentGradebookEntry ||--o{ StudentSectionAssociation : "has associated"
    StudentSectionAssociation ||--o{ Student : "has associated"
    Student ||--o{ Section : "has associated"
