---
title: TeachingAndLearning
config:
  layout: elk
---
erDiagram
    EducationOrganization {
        integer EducationOrganizationId "I"
        string NameOfInstitution "R"
        string ShortNameOfInstitution "O"
        descriptor EducationOrganizationCategory "RC"
        common Address "OC"
        common InternationalAddress "OC"
        common InstitutionTelephone "OC"
        string WebSite "O"
        descriptor OperationalStatus "O"
        common EducationOrganizationIndicator "OC"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor CharterStatus "O"
        descriptor TitleIPartASchoolDesignation "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        descriptor AdministrativeFundingControl "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor FederalLocaleCode "O"
        reference PostSecondaryInstitution "O"
        bool ImprovingSchool "O"
        descriptor AccreditationStatus "O"
    }
    Session {
        string SessionName "I"
        enumeration SchoolYear "I"
        reference School "I"
        date BeginDate "R"
        date EndDate "R"
        descriptor Term "R"
        integer TotalInstructionalDays "R"
        reference GradingPeriod "OC"
        reference AcademicWeek "OC"
    }
    Student {
        string StudentUniqueId "I"
        common Name "R"
        common BirthData "R"
        common OtherName "OC"
        reference Person "O"
    }
    Staff {
        string StaffUniqueId "I"
        common Name "R"
        common OtherName "OC"
        date BirthDate "O"
        descriptor HighestCompletedLevelOfEducation "O"
        decimal YearsOfPriorProfessionalExperience "O"
        decimal YearsOfPriorTeachingExperience "O"
        string LoginId "O"
        bool HighlyQualifiedTeacher "O"
        common Recognition "OC"
        reference Credential "OC"
        reference Person "O"
        descriptor HighlyQualifiedAcademicSubject "OC"
        common EducatorResearch "O"
        reference EducatorPreparationProgram "OC"
        reference OpenStaffPosition "O"
    }
    Course {
        string CourseCode "I"
        reference EducationOrganization "I"
        string CourseTitle "R"
        integer NumberOfParts "R"
        common CourseIdentificationCode "RC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor OfferedGradeLevel "OC"
        descriptor AcademicSubject "OC"
        descriptor CompetencyLevel "OC"
        reference LearningStandard "OC"
        string CourseDescription "O"
        integer TimeRequiredForCompletion "O"
        date DateCourseAdopted "O"
        bool HighSchoolCourseRequirement "O"
        descriptor CourseGPAApplicability "O"
        descriptor CourseDefinedBy "O"
        common MinimumAvailableCredits "O"
        common MaximumAvailableCredits "O"
        descriptor CareerPathway "O"
        integer MaxCompletionsForCredit "O"
    }
    CourseOffering {
        string LocalCourseCode "I"
        reference School "I"
        reference Session "I"
        reference Course "R"
        string LocalCourseTitle "O"
        integer InstructionalTimePlanned "O"
        descriptor CurriculumUsed "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor OfferedGradeLevel "OC"
    }
    Section {
        string SectionIdentifier "I"
        reference CourseOffering "I"
        descriptor SectionType "O"
        integer SequenceOfCourse "O"
        descriptor EducationalEnvironment "O"
        descriptor MediumOfInstruction "O"
        descriptor PopulationServed "O"
        common AvailableCredits "O"
        descriptor SectionCharacteristic "OC"
        descriptor InstructionLanguage "O"
        reference LocationSchool "O"
        reference Location "O"
        reference ClassPeriod "OC"
        reference Program "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor OfferedGradeLevel "OC"
        bool OfficialAttendancePeriod "O"
        string SectionName "O"
    }
    ClassPeriod {
        reference School "I"
        string ClassPeriodName "I"
        common MeetingTime "OC"
        bool OfficialAttendancePeriod "O"
    }
    Location {
        reference School "I"
        string ClassroomIdentificationCode "I"
        integer MaximumNumberOfSeats "O"
        integer OptimalNumberOfSeats "O"
    }
    Program {
        reference EducationOrganization "I"
        string ProgramName "I"
        descriptor ProgramType "I"
        string ProgramId "O"
        descriptor ProgramCharacteristic "OC"
        descriptor ProgramSponsor "OC"
        reference LearningStandard "OC"
    }
    LearningStandard {
        string LearningStandardId "I"
        string Description "R"
        common ContentStandard "R"
        string Namespace "R"
        descriptor GradeLevel "RC"
        descriptor AcademicSubject "RC"
        common LearningStandardIdentificationCode "OC"
        string LearningStandardItemCode "O"
        string URI "O"
        string CourseTitle "O"
        string SuccessCriteria "O"
        reference ParentLearningStandard "O"
        descriptor LearningStandardCategory "O"
        descriptor LearningStandardScope "O"
    }
    StudentSchoolAssociation {
        reference Student "I"
        reference School "I"
        date EntryDate "I"
        descriptor EntryGradeLevel "R"
        bool PrimarySchool "O"
        enumeration SchoolYear "O"
        descriptor EntryGradeLevelReason "O"
        descriptor EntryType "O"
        bool RepeatGradeIndicator "O"
        enumeration ClassOfSchoolYear "O"
        bool SchoolChoiceTransfer "O"
        date ExitWithdrawDate "O"
        descriptor ExitWithdrawType "O"
        descriptor EducationPlan "OC"
        descriptor ResidencyStatus "O"
        reference GraduationPlan "O"
        reference AlternativeGraduationPlan "OC"
        bool EmployedWhileEnrolled "O"
        reference Calendar "O"
        decimal FullTimeEquivalency "O"
        bool TermCompletionIndicator "O"
        reference NextYearSchool "O"
        descriptor NextYearGradeLevel "O"
        bool SchoolChoice "O"
        descriptor SchoolChoiceBasis "O"
        descriptor EnrollmentType "O"
    }
    StaffSchoolAssociation {
        reference Staff "I"
        reference School "I"
        descriptor ProgramAssignment "I"
        enumeration SchoolYear "O"
        descriptor GradeLevel "OC"
        descriptor AcademicSubject "OC"
        reference Calendar "O"
    }
    StaffProgramAssociation {
        reference Staff "I"
        reference Program "I"
        date BeginDate "I"
        date EndDate "O"
        bool StudentRecordAccess "O"
    }
    GeneralStudentProgramAssociation {
        reference Student "I"
        reference Program "I"
        reference EducationOrganization "I"
        date BeginDate "I"
        date EndDate "O"
        descriptor ReasonExited "O"
        bool ServedOutsideOfRegularSession "O"
        common ProgramParticipationStatus "OC"
    }
    StudentSectionAssociation {
        reference Student "I"
        reference Section "I"
        date BeginDate "I"
        date EndDate "O"
        bool HomeroomIndicator "O"
        descriptor RepeatIdentifier "O"
        bool TeacherStudentDataLinkExclusion "O"
        descriptor AttemptStatus "O"
        reference Program "OC"
        common DualCredit "O"
    }
    StaffSectionAssociation {
        reference Staff "I"
        reference Section "I"
        date BeginDate "I"
        descriptor ClassroomPosition "R"
        date EndDate "O"
        bool HighlyQualifiedTeacher "O"
        bool TeacherStudentDataLinkExclusion "O"
        percent PercentageContribution "O"
    }

    School ||--o{ EducationOrganization : "extends"
    EducationOrganization ||--o{ Session : "has associated"
    EducationOrganization ||--o{ School : "has associated"
    EducationOrganization ||--o{ Course : "has associated"
    Student ||--o{ StudentSchoolAssociation : "ParticipatesIn"
    Student ||--o{ GeneralStudentProgramAssociation : "participates in"
    Student ||--o{ StudentSectionAssociation : "participates in"
    Staff ||--o{ StaffSchoolAssociation : "has associated"
    Staff ||--o{ StaffProgramAssociation : "has associated"
    Staff ||--o{ StaffSectionAssociation : "has associated"
    School ||--o{ StudentSchoolAssociation : "has associated"
    School ||--o{ StaffSchoolAssociation : "has associated"
    School ||--o{ Session : "has associated"
    Program ||--o{ GeneralStudentProgramAssociation : "has associated"
    Program ||--o{ StaffProgramAssociation : "has associated"
    EducationOrganization ||--o{ GeneralStudentProgramAssociation : "has associated"
    Course ||--o{ CourseOffering : "has associated"
    School ||--o{ CourseOffering : "has associated"
    CourseOffering ||--o{ Section : "has associated"
    Section ||--o{ StudentSectionAssociation : "has associated"
    Section ||--o{ StaffSectionAssociation : "has associated"
    Section ||--o{ ClassPeriod : "has functional component"
    Section ||--o{ Location : "has associated"
    LearningStandard ||--o{ Section : "has associated"
    LearningStandard ||--o{ LearningStandard : "has associated equivalence"
    LearningStandard ||--o{ Course : "has associated"
