---
title: TeachingAndLearning-CourseCatalog
config:
  layout: elk
---
erDiagram
    EducationOrganization {
        integer EducationOrganizationId "I"
        string NameOfInstitution "R"
        string ShortNameOfInstitution "O"
        descriptor EducationOrganizationCategory "RC"
        common Address "OC"
        common InternationalAddress "OC"
        common InstitutionTelephone "OC"
        string WebSite "O"
        descriptor OperationalStatus "O"
        common EducationOrganizationIndicator "OC"
    }
    School {
        integer SchoolId "I"
        descriptor GradeLevel "RC"
        descriptor SchoolCategory "OC"
        descriptor SchoolType "O"
        descriptor CharterStatus "O"
        descriptor TitleIPartASchoolDesignation "O"
        descriptor MagnetSpecialProgramEmphasisSchool "O"
        descriptor AdministrativeFundingControl "O"
        descriptor InternetAccess "O"
        reference LocalEducationAgency "O"
        descriptor CharterApprovalAgencyType "O"
        enumeration CharterApprovalSchoolYear "O"
        descriptor FederalLocaleCode "O"
        reference PostSecondaryInstitution "O"
        bool ImprovingSchool "O"
        descriptor AccreditationStatus "O"
    }
    Session {
        string SessionName "I"
        enumeration SchoolYear "I"
        reference School "I"
        date BeginDate "R"
        date EndDate "R"
        descriptor Term "R"
        integer TotalInstructionalDays "R"
        reference GradingPeriod "OC"
        reference AcademicWeek "OC"
    }
    Course {
        string CourseCode "I"
        reference EducationOrganization "I"
        string CourseTitle "R"
        integer NumberOfParts "R"
        common CourseIdentificationCode "RC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor OfferedGradeLevel "OC"
        descriptor AcademicSubject "OC"
        descriptor CompetencyLevel "OC"
        reference LearningStandard "OC"
        string CourseDescription "O"
        integer TimeRequiredForCompletion "O"
        date DateCourseAdopted "O"
        bool HighSchoolCourseRequirement "O"
        descriptor CourseGPAApplicability "O"
        descriptor CourseDefinedBy "O"
        common MinimumAvailableCredits "O"
        common MaximumAvailableCredits "O"
        descriptor CareerPathway "O"
        integer MaxCompletionsForCredit "O"
    }
    CourseOffering {
        string LocalCourseCode "I"
        reference School "I"
        reference Session "I"
        reference Course "R"
        string LocalCourseTitle "O"
        integer InstructionalTimePlanned "O"
        descriptor CurriculumUsed "OC"
        descriptor CourseLevelCharacteristic "OC"
        descriptor OfferedGradeLevel "OC"
    }
    LearningStandard {
        string LearningStandardId "I"
        string Description "R"
        common ContentStandard "R"
        string Namespace "R"
        descriptor GradeLevel "RC"
        descriptor AcademicSubject "RC"
        common LearningStandardIdentificationCode "OC"
        string LearningStandardItemCode "O"
        string URI "O"
        string CourseTitle "O"
        string SuccessCriteria "O"
        reference ParentLearningStandard "O"
        descriptor LearningStandardCategory "O"
        descriptor LearningStandardScope "O"
    }

    School ||--o{ EducationOrganization : "extends"
    EducationOrganization ||--o{ Course : "has associated"
    School ||--o{ Session : "has associated"
    School ||--o{ CourseOffering : "has associated"
    Session ||--o{ CourseOffering : "has associated"
    Course ||--o{ CourseOffering : "has associated"
    Course ||--o{ LearningStandard : "has associated"
    LearningStandard ||--o{ LearningStandard : "has functional component"
    LearningStandard ||--o{ LearningStandard : "has associated equivalence"
